# 01 - Data prep (Data Rescue Project)
github: https://github.com/datarescueproject/portal/

Here I collected the metadata from DRP, recovered DOIs, and enriched with metadata. This notebook covers the $red$ part of the DRP preprocessing pipeline:

<p align="center">
  <img src="00_figures/drp_preprocessing_01.png"
       alt="DRP preprocessing pipeline"
       title="DRP Preprocessing pipeline, part covered in the notebook in red."
       height="600">
</p>

### Imports

In [ ]:
import sys
from pathlib import Path

PROJECT_ROOT = Path().resolve().parent
sys.path.append(str(PROJECT_ROOT))

from general.util.banned_words import add_flagged_column

In [ ]:
import re
import requests
import yaml
import pandas as pd
from bs4 import BeautifulSoup
from playwright.async_api import async_playwright
from urllib.parse import urlparse, unquote
import time
from general.util.banned_words import add_flagged_column


pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

## Scraping DRP Portal Github for data md files

In [ ]:
owner = 'datarescueproject'
repo = 'portal'
repo_url = f'https://github.com/datarescueproject/portal/'
folder = '_datasets/'
branch = 'main'

In [ ]:
ref = requests.get(f'https://api.github.com/repos/datarescueproject/portal/git/refs/heads/{branch}').json()
commit_sha = ref['object']['sha']
tree_sha = requests.get(f'https://api.github.com/repos/datarescueproject/portal/git/commits/{commit_sha}').json()['tree']['sha']
tree = requests.get(f'https://api.github.com/repos/datarescueproject/portal/git/trees/{tree_sha}', params={'recursive':'1'}).json()['tree']

In [ ]:
md_files = []
for item in tree:
    if item['type'] != 'blob':
        continue
    if not item['path'].startswith(folder):
        continue
    if not item['path'].lower().endswith('.md'):
        continue
    md_files.append(item['path'])

md_files = sorted(md_files)
print(len(md_files))

2972

In [8]:
frontmatter_regex = re.compile(
    r'^\s*---\s*\n(.*?)\n---\s*\n?',
    re.DOTALL
)

projects = []
resources = []

for path in md_files:
    raw_url = f'https://raw.githubusercontent.com/datarescueproject/portal/main/{path}'
    markdown = requests.get(raw_url).text

    match = frontmatter_regex.match(markdown)
    if not match:
        frontmatter = {}
    else:
        frontmatter = yaml.safe_load(match.group(1)) or {}

    if not isinstance(frontmatter, dict):
        frontmatter = {}

    project_row = {
        'file': path,
        'schema': frontmatter.get('schema'),
        'title': frontmatter.get('title'),
        'organization': frontmatter.get('organization'),
        'agency': frontmatter.get('agency'),
        'websites': frontmatter.get('websites'),
        'data_source': frontmatter.get('data_source'),
        'description': frontmatter.get('description'),
        'last_modified': frontmatter.get('last_modified'),
        'metadata_available': frontmatter.get('metadata_available'),
        'metadata_url': frontmatter.get('metadata_url'),
    }

    categories = frontmatter.get('category', [])
    if isinstance(categories, list):
        project_row['category'] = '; '.join(map(str, categories))
    elif categories:
        project_row['category'] = str(categories)
    else:
        project_row['category'] = ''

    resource_list = frontmatter.get('resources', [])
    if not isinstance(resource_list, list):
        resource_list = []

    project_row['resource_count'] = len(resource_list)
    projects.append(project_row)

    for res in resource_list:
        if not isinstance(res, dict):
            continue

        resources.append({
            'file': path,
            'project_title': frontmatter.get('title'),
            'id': res.get('id'),
            'url': res.get('url'),
            'format': res.get('format'),
            'status': res.get('status'),
            'size': res.get('size'),
            'download_date': res.get('download_date'),
            'maintainer': res.get('maintainer'),
            'notes': res.get('notes'),
        })

projects_df = pd.DataFrame(projects)
resources_df = pd.DataFrame(resources)

projects_df.head(2)

KeyboardInterrupt:

### Saving

In [ ]:
projects_df.to_csv('00_data/datarescuetracker.csv')
resources_df.to_csv('00_data/resources.csv')

In [9]:
projects_df = pd.read_csv('00_data/datarescuetracker.csv')
resources_df = pd.read_csv('00_data/resources.csv')

In [10]:
projects_df.head(2)

,Unnamed: 0,file,schema,title,organization,agency,websites,data_source,description,last_modified,metadata_available,metadata_url,category,resource_count
0,0,_datasets/10j-injunctions.md,data_rescue_project,10(j) Injunctions,National Labor Relations Board,National Labor Relations Board,nlrb.gov,https://www.nlrb.gov/what-we-do/investigate-charges/10j-injunctions,NaN,2025-04-20,True,NaN,Labor & Employment,1
1,1,_datasets/1998-2023-serotype-data-for-invasive-pneumococcal-disease-cases-by-age-group-from-active-bacterial-core-surveillance.md,data_rescue_project,1998-2023 Serotype Data for Invasive Pneumococcal Disease Cases by Age Group from Active Bacterial Core surveillance,Centers for Disease Control and Prevention (CDC),Department of Health and Human Services,data.cdc.gov,https://data.cdc.gov/Public-Health-Surveillance/1998-2023-Serotype-Data-for-Invasive-Pneumococcal-/qvzb-qs6p/about_data,NaN,2026-01-25,False,NaN,Health & Healthcare,1

In [11]:
projects_df.shape

(2958, 14)

Creating single df

In [12]:
df = pd.merge(projects_df, resources_df, on='file')

In [10]:
df.head(1)

,Unnamed: 0_x,file,schema,title,organization,agency,websites,data_source,description,last_modified,metadata_available,metadata_url,category,resource_count,Unnamed: 0_y,project_title,id,url,format,status,size,download_date,maintainer,notes
0,0,_datasets/10j-injunctions.md,data_rescue_project,10(j) Injunctions,National Labor Relations Board,National Labor Relations Board,nlrb.gov,https://www.nlrb.gov/what-we-do/investigate-charges/10j-injunctions,NaN,2025-04-20,True,NaN,Labor & Employment,1,0,10(j) Injunctions,759,https://doi.org/10.3886/E226824V1,"CSV, TXT",Finished,0.0,2025-04-07,"DRP, DL","Section 10(j) of the National Labor Relations Act authorizes the National Labor Relations Board to seek temporary injunctions against employers and unions in federal district courts to stop unfair labor practices while the case is being litigated before administrative law judges and the Board. These temporary injunctions are needed to protect the process of collective bargaining and employee rights under the Act, and to ensure that Board decisions will be meaningful. The section was added as part of a set of reforms to the Act in 1947. Over the years, all NLRB General Counsels have made use of this effective enforcement tool, as shown in this chart.The csv contains Authorization Dates, Case Numbers, Case Names, and Injunction Status as of the date collected (2025-04-07). This list is all 10(j) injunction cases authorized by the Board since September 1, 2010."

In [15]:
df.to_csv('00_data/df_scraped.csv')

In [14]:
df.isna().mean()

Unnamed: 0_x          0.000000
file                  0.000000
schema                0.000000
title                 0.000000
organization          0.000000
agency                0.000331
websites              0.000331
data_source           0.000331
description           0.996692
last_modified         0.000000
metadata_available    0.000000
metadata_url          0.953688
category              0.000331
resource_count        0.000000
Unnamed: 0_y          0.000000
project_title         0.000000
id                    0.000000
url                   0.014886
format                0.175984
status                0.000000
size                  0.105855
download_date         0.043004
maintainer            0.000000
notes                 0.718492
dtype: float64

## Getting more metadata: DOI guesses

### Domain extraction

In [11]:
def get_domain(url):
    if not isinstance(url, str):
        return None
    return urlparse(url).netloc

In [ ]:
df['domain'] = df['url'].apply(get_domain)
df.head(2)

,Unnamed: 0_x,file,schema,title,organization,agency,websites,data_source,description,last_modified,metadata_available,metadata_url,category,resource_count,Unnamed: 0_y,project_title,id,url,format,status,size,download_date,maintainer,notes,domain
0,0,_datasets/10j-injunctions.md,data_rescue_project,10(j) Injunctions,National Labor Relations Board,National Labor Relations Board,nlrb.gov,https://www.nlrb.gov/what-we-do/investigate-charges/10j-injunctions,NaN,2025-04-20,True,NaN,Labor & Employment,1,0,10(j) Injunctions,759,https://doi.org/10.3886/E226824V1,"CSV, TXT",Finished,0.0000,2025-04-07,"DRP, DL","Section 10(j) of the National Labor Relations Act authorizes the National Labor Relations Board to seek temporary injunctions against employers and unions in federal district courts to stop unfair labor practices while the case is being litigated before administrative law judges and the Board. These temporary injunctions are needed to protect the process of collective bargaining and employee rights under the Act, and to ensure that Board decisions will be meaningful. The section was added as part of a set of reforms to the Act in 1947. Over the years, all NLRB General Counsels have made use of this effective enforcement tool, as shown in this chart.The csv contains Authorization Dates, Case Numbers, Case Names, and Injunction Status as of the date collected (2025-04-07). This list is all 10(j) injunction cases authorized by the Board since September 1, 2010.",doi.org
1,1,_datasets/1998-2023-serotype-data-for-invasive-pneumococcal-disease-cases-by-age-group-from-active-bacterial-core-surveillance.md,data_rescue_project,1998-2023 Serotype Data for Invasive Pneumococcal Disease Cases by Age Group from Active Bacterial Core surveillance,Centers for Disease Control and Prevention (CDC),Department of Health and Human Services,data.cdc.gov,https://data.cdc.gov/Public-Health-Surveillance/1998-2023-Serotype-Data-for-Invasive-Pneumococcal-/qvzb-qs6p/about_data,NaN,2026-01-25,False,NaN,Health & Healthcare,1,1,1998-2023 Serotype Data for Invasive Pneumococcal Disease Cases by Age Group from Active Bacterial Core surveillance,2256,https://www.datalumos.org/datalumos/project/243434/version/V1/view,"PDF, CSV",Finished,0.0009,2026-01-10,"DRP, DL",NaN,www.datalumos.org

In [13]:
df['domain'].value_counts()

domain
www.datalumos.org                                2586
www.dropbox.com                                    85
sciop.net                                          72
doi.org                                            49
dataverse.harvard.edu                              46
zenodo.org                                         34
archive.org                                        28
github.com                                         22
urban-data-catalog.s3.us-east-1.amazonaws.com      10
purl.stanford.edu                                  10
nlrbresearch.com                                    4
web.archive.org                                     3
arcgis.com                                          3
www.openicpsr.org                                   3
www.arcgis.com                                      3
biglocalnews.org                                    3
doi.pangaea.de                                      2
www.hydroshare.org                                  1
s3.amazonaws.com                                    1
tables.codeberg.page                                1
www.thelgbtqarchive.org                             1
box.hu-berlin.de                                    1
www.zelma.ai                                        1
www.documentcloud.org                               1
gofile.me                                           1
public.tableau.com                                  1
edgi-govdata-archiving.github.io                    1
erica.datarescueproject.org                         1
hub.arcgis.com                                      1
source.coop                                         1
livingatlas.arcgis.com                              1
data.openei.org                                     1
Name: count, dtype: int64

In [14]:
df[df['domain'].isna()].head(2)

,Unnamed: 0_x,file,schema,title,organization,agency,websites,data_source,description,last_modified,metadata_available,metadata_url,category,resource_count,Unnamed: 0_y,project_title,id,url,format,status,size,download_date,maintainer,notes,domain
242,233,_datasets/bipartisan-infrastructure-law-and-inflation-reduction-act-awards-explorer.md,data_rescue_project,Bipartisan Infrastructure Law and Inflation Reduction Act Awards Explorer,National Oceanic and Atmospheric Administration,Department of Commerce,noaa.gov,https://www.noaa.gov/bil-ira-awards-explorer,NaN,2025-03-02,False,NaN,Climate & Environment,1,242,Bipartisan Infrastructure Law and Inflation Reduction Act Awards Explorer,211,NaN,CSV,Finished,0.0,NaN,"EDGI, ESRI",Local - EDGI; only downloaded the csv; not trying to recreate the mapper,None
243,234,_datasets/bls-downloads.md,data_rescue_project,BLS Downloads,Bureau of Labor Statistics,Department of Labor,download.bls.gov,https://download.bls.gov,NaN,2025-02-10,False,NaN,Labor & Employment; Business & Economy,1,243,BLS Downloads,1,NaN,NaN,In Progress,47.0,2025-02-01,DRP,NaN,None

## Scraping datalumos for metadata (didnt work)

In [ ]:
!pip -q install playwright beautifulsoup4 lxml
!playwright install chromium

^C
Traceback (most recent call last):
  File "/opt/anaconda3/envs/env12/lib/python3.12/pathlib.py", line 441, in __str__
    return self._str
           ^^^^^^^^^
AttributeError: 'PosixPath' object has no attribute '_str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/env12/lib/python3.12/pathlib.py", line 555, in drive
    return self._drv
           ^^^^^^^^^
AttributeError: 'PosixPath' object has no attribute '_drv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/env12/bin/pip", line 11, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/anaconda3/envs/env12/lib/python3.12/site-packages/pip/_internal/cli/main.py", line 79, in main
    return command.main(cmd_args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/env12/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 101, in main
    return self._main(args)
           ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/env12/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 236, in _main
    self.handle_pip_version_check(options)
  File "/opt/anaconda3/envs/env12/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 188, in handle_pip_version_check
    pip_self_version_check(session, options)
  File "/opt/anaconda3/envs/env12/lib/python3.12/site-packages/pip/_internal/self_outdated_check.py", line 231, in pip_self_version_check
    installed_dist = get_default_environment().get_distribution("pip")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/env12/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 189, in get_distribution
    return next(matches, None)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/env12/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 184, in <genexpr>
    matches = (
              ^
  File "/opt/anaconda3/envs/env12/lib/python3.12/site-packages/pip/_internal/metadata/base.py", line 626, in iter_all_distributions
    for dist in self._iter_distributions():
  File "/opt/anaconda3/envs/env12/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 176, in _iter_distributions
    yield from finder.find(location)
  File "/opt/anaconda3/envs/env12/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 79, in find
    for dist, info_location in self._find_impl(location):
  File "/opt/anaconda3/envs/env12/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 64, in _find_impl
    raw_name = get_dist_name(dist)
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/env12/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_compat.py", line 52, in get_dist_name
    name = cast(Any, dist).name
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/env12/lib/python3.12/importlib/metadata/__init__.py", line 457, in name
    return self.metadata['Name']
           ^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/env12/lib/python3.12/importlib/metadata/__init__.py", line 444, in metadata
    self.read_text('METADATA')
  File "/opt/anaconda3/envs/env12/lib/python3.12/importlib/metadata/__init__.py", line 819, in read_text
    return self._path.joinpath(filename).read_text(encoding='utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/env12/lib/python3.12/pathlib.py", line 1027, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/env12/lib/python3.12/pathlib.py", line 1013, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/env12/lib/python3.12/pathlib.py", line 448, in __fspath__
    return str(self)
           ^^^^^^^^^
  File "/opt/anaconda3/envs/env12/lib/python3.12/pathlib.py", line 443, in __str__
    self._str = self._format_parsed_parts(self.drive, self.root,
                                          ^^^^^^^^^^
  File "/opt/anaconda3/envs/env12/lib/python3.12/pathlib.py", line 557, in drive
    self._load_parts()
  File "/opt/anaconda3/envs/env12/lib/python3.12/pathlib.py", line 414, in _load_parts
    path = self._flavour.join(*paths)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 85, in join
KeyboardInterrupt

In [ ]:
doi_re = re.compile(r'(?:doi\.org/|doi:\s*)(10\.\d{4,9}/[-._;()/:A-Z0-9]+)', re.I)

mask = resources_df['domain'].isin(['www.datalumos.org', 'datalumos.org'])
cols = ['principal_investigators','summary','project_title_page','geographic_coverage','time_periods','doi']
resources_df.loc[mask, cols] = None

async with async_playwright() as p:
    browser = await p.chromium.launch(headless=True)
    page = await browser.new_page()

    for i, row in resources_df[mask].iterrows():
        url = row['url']
        print(url)
        try:
            await page.goto(url, wait_until='networkidle', timeout=60000)
            html = await page.content()
            soup = BeautifulSoup(html, 'lxml')

            # scan all <strong> labels and capture the text in the same parent
            for strong in soup.find_all('strong'):
                label = strong.get_text(' ', strip=True)
                parent_text = strong.parent.get_text(' ', strip=True)
                value = re.sub(rf'^{re.escape(label)}\s*:?\s*', '', parent_text).strip()

                low = label.lower()
                if 'principal investigator' in low:
                    resources_df.at[i, 'principal_investigators'] = value
                elif low.startswith('summary'):
                    resources_df.at[i, 'summary'] = value
                elif low.startswith('project title'):
                    resources_df.at[i, 'project_title_page'] = value
                elif low.startswith('geographic coverage'):
                    resources_df.at[i, 'geographic_coverage'] = value
                elif low.startswith('time period'):
                    resources_df.at[i, 'time_periods'] = value

            text = soup.get_text(' ', strip=True)
            found = doi_re.findall(text)
            if found:
                resources_df.at[i, 'doi'] = found[0]

        except Exception as e:
            print('Failed:', url, '|', e)

    await browser.close()

resources_df.loc[mask, ['url'] + cols].head()

In [ ]:
from playwright.async_api import async_playwright

test_url = resources_df.loc[mask, 'url'].dropna().iloc[0]
print('Testing:', test_url)

async with async_playwright() as p:
    browser = await p.chromium.launch(headless=True)
    page = await browser.new_page()
    await page.goto(test_url, timeout=60000)
    print(await page.title())
    await browser.close()

## Filling in DOI column if DOI provided as url

In [15]:
dois_provided = df['domain'] == 'doi.org'

In [ ]:
doi_pattern = r'(10\.\d{4,9}/[-._;()/:a-z0-9]+)'

df.loc[dois_provided, 'doi'] = (
    df.loc[dois_provided, 'url']
      .str.lower()
      .str.extract(doi_pattern, expand=False)
)

In [17]:
df['doi'].isna().mean()

0.9837909361561363

## Extacting DOI of datalumos projects from urls

In [ ]:
m = df['url'].astype(str).str.extract(r'/project/(\d+)/version/(V\d+)/', expand=True)
df['project_id'] = m[0]
df['version'] = m[1]

# guessing DOI in the common ICPSR style: 10.3886/E{project_id}{version}
df['doi_guess'] = None
mask_dl = df['domain'].isin(['www.datalumos.org', 'datalumos.org']) & df['project_id'].notna() & df['version'].notna()
df.loc[mask_dl, 'doi_guess'] = '10.3886/E' + df.loc[mask_dl, 'project_id'] + df.loc[mask_dl, 'version']

df.loc[mask_dl, ['url','project_id','version','doi_guess']]

,url,project_id,version,doi_guess
1,https://www.datalumos.org/datalumos/project/243434/version/V1/view,243434,V1,10.3886/E243434V1
2,https://www.datalumos.org/datalumos/project/223443/version/V1/view,223443,V1,10.3886/E223443V1
4,https://www.datalumos.org/datalumos/project/244041/version/V1/view,244041,V1,10.3886/E244041V1
5,https://www.datalumos.org/datalumos/project/222881/version/V1/view,222881,V1,10.3886/E222881V1
6,https://www.datalumos.org/datalumos/project/222043/version/V1/view,222043,V1,10.3886/E222043V1
...,...,...,...,...
3009,https://www.datalumos.org/datalumos/project/227293/version/V1/view,227293,V1,10.3886/E227293V1
3010,https://www.datalumos.org/datalumos/project/227006/version/V1/view,227006,V1,10.3886/E227006V1
3016,https://www.datalumos.org/datalumos/project/223063/version/V1/view,223063,V1,10.3886/E223063V1
3020,https://www.datalumos.org/datalumos/project/242851/version/V1/view,242851,V1,10.3886/E242851V1
3021,https://www.datalumos.org/datalumos/project/244042/version/V1/view,244042,V1,10.3886/E244042V1

In [19]:
df['doi_guess'].value_counts()

doi_guess
10.3886/E222581V1    51
10.3886/E223141V1    48
10.3886/E229201V1    37
10.3886/E223001V1    30
10.3886/E224621V1    25
                     ..
10.3886/E240201V1     1
10.3886/E239792V1     1
10.3886/E239983V1     1
10.3886/E239798V1     1
10.3886/E244042V1     1
Name: count, Length: 1965, dtype: int64

Testing if it works

In [ ]:
test = '10.3886/E223443V1'

url = f'https://api.datacite.org/dois/{test}'

headers = {
    'Accept': 'application/vnd.api+json'
}

response = requests.get(url, headers=headers)

print(response.text)

{"data":{"id":"10.3886/e223443v1","type":"dois","attributes":{"doi":"10.3886/e223443v1","prefix":"10.3886","suffix":"e223443v1","identifiers":[],"alternateIdentifiers":[],"creators":[{"name":"United States Department Of Commerce. Minority Business Development Agency","nameType":"Organizational","affiliation":[],"nameIdentifiers":[]}],"titles":[{"lang":"en","title":"2022-2024 MBDA Grantees"}],"publisher":"ICPSR - Interuniversity Consortium for Political and Social Research","container":{},"publicationYear":2025,"subjects":[{"lang":"en","subject":"grants"},{"lang":"en","subject":"minority businesses"}],"contributors":[],"dates":[{"date":"2022-01-01/2024-12-31","dateType":"Collected"},{"date":"2025","dateType":"Issued"}],"language":"en","types":{"ris":"DATA","bibtex":"misc","citeproc":"dataset","schemaOrg":"Dataset","resourceTypeGeneral":"Dataset"},"relatedIdentifiers":[{"relationType":"IsVersionOf","relatedIdentifier":"10.3886/e223443","relatedIdentifierType":"DOI"}],"relatedItems":[],"sizes":[],"formats":[],"version":"v1","rightsList":[],"descriptions":[{"lang":"en","description":"This dataset contains public information on grantees of the Minority Business Development Agency (MBDA) programs, covering grants awarded since 2022. It includes data on all grant-funded centers across all MBDA programs, providing information on each grantee’s including location, contact details, service area, and its associated MBDA program.\u003cbr\u003e\u003cbr\u003eAdditional information includes the status of each grantee (whether they are currently funded and operating), grant award identifiers, and a brief description of the grantees services and specialities. Detailed information is provided in the data schema provided below.\u003cbr\u003e\u003cbr\u003eMBDA’s mission is to promote the growth and global competitiveness of Minority Business Enterprises (MBE) in order to unlock the country’s full economic potential. MBDA programs provide support for MBEs through a variety of services aimed at improving access to capital, contracts, and markets. These programs help entrepreneurs overcome barriers to success and expand their businesses by offering tailored technical assistance, business consulting, and access to networks.\u003cbr\u003e\u003cbr\u003eNote: the original website is titled 2002-2024 grantees but the description refers to grants awarded since 2022\u003cbr\u003e","descriptionType":"Abstract"}],"geoLocations":[{"geoLocationPlace":"U.S. Territories"},{"geoLocationPlace":"U.S. States"}],"fundingReferences":[],"xml":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/Pgo8cmVzb3VyY2UgeG1sbnM9Imh0dHA6Ly9kYXRhY2l0ZS5vcmcvc2NoZW1hL2tlcm5lbC00IiB4bWxuczp4c2k9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hLWluc3RhbmNlIiB4c2k6c2NoZW1hTG9jYXRpb249Imh0dHA6Ly9kYXRhY2l0ZS5vcmcvc2NoZW1hL2tlcm5lbC00IGh0dHBzOi8vc2NoZW1hLmRhdGFjaXRlLm9yZy9tZXRhL2tlcm5lbC00LjMvbWV0YWRhdGEueHNkIj4KICA8aWRlbnRpZmllciBpZGVudGlmaWVyVHlwZT0iRE9JIj4xMC4zODg2L0UyMjM0NDNWMTwvaWRlbnRpZmllcj4KICA8Y3JlYXRvcnM+CiAgICA8Y3JlYXRvcj4KICAgICAgPGNyZWF0b3JOYW1lIG5hbWVUeXBlPSJPcmdhbml6YXRpb25hbCI+VW5pdGVkIFN0YXRlcyBEZXBhcnRtZW50IG9mIENvbW1lcmNlLiBNaW5vcml0eSBCdXNpbmVzcyBEZXZlbG9wbWVudCBBZ2VuY3k8L2NyZWF0b3JOYW1lPgogICAgPC9jcmVhdG9yPgogIDwvY3JlYXRvcnM+CiAgPHRpdGxlcz4KICAgIDx0aXRsZSB4bWw6bGFuZz0iZW4iPjIwMjItMjAyNCBNQkRBIEdyYW50ZWVzPC90aXRsZT4KICA8L3RpdGxlcz4KICA8cHVibGlzaGVyPklDUFNSIC0gSW50ZXJ1bml2ZXJzaXR5IENvbnNvcnRpdW0gZm9yIFBvbGl0aWNhbCBhbmQgU29jaWFsIFJlc2VhcmNoPC9wdWJsaXNoZXI+CiAgPHB1YmxpY2F0aW9uWWVhcj4yMDI1PC9wdWJsaWNhdGlvblllYXI+CiAgPHJlc291cmNlVHlwZSByZXNvdXJjZVR5cGVHZW5lcmFsPSJEYXRhc2V0Ii8+CiAgPHN1YmplY3RzPgogICAgPHN1YmplY3QgeG1sOmxhbmc9ImVuIj5ncmFudHM8L3N1YmplY3Q+CiAgICA8c3ViamVjdCB4bWw6bGFuZz0iZW4iPm1pbm9yaXR5IGJ1c2luZXNzZXM8L3N1YmplY3Q+CiAgPC9zdWJqZWN0cz4KICA8ZGF0ZXM+CiAgICA8ZGF0ZSBkYXRlVHlwZT0iQ29sbGVjdGVkIj4yMDIyLTAxLTAxLzIwMjQtMTItMzE8L2RhdGU+CiAgPC9kYXRlcz4KICA8bGFuZ3VhZ2U+ZW5nPC9sYW5ndWFnZT4KICA8cmVsYXRlZElkZW50aWZpZXJzPgogICAgPHJlbGF0ZWRJZGVudGlmaWVyIHJlbGF0ZWRJZGVudGlmaWVyVHlwZT0iRE9JIiByZWxhdGlvblR5cGU9IklzVmVyc2lvbk9mIj4xMC4zODg2L0UyMjM0NDM8L3JlbGF0ZWRJZGVudGlmaWVyPgogIDwvcmVsYXRlZElkZW50aWZpZXJzPgogIDx2ZXJzaW9uPnYxPC92ZXJzaW9uPgogIDxkZXNjcmlwdGlvbnM+CiAgICA8ZGVzY3JpcHRpb24gZGVzY3JpcHRpb25UeXBlPSJBYnN0cmFjdCIgeG1sOmxhbmc9ImVuIj5UaGlzIGRhdGFzZXQgY29udGFpbnMgcHVibGljIGluZm9ybWF0aW9uIG9uIGdyYW50ZWVzIG9mIHRoZSBNaW5vcml0eSBCdXNpbmVzcyBEZXZlbG9wbWVudCBBZ2VuY3kgKE1CREEpIHByb2dyYW1zLCBjb3ZlcmluZyBncmFudHMgYXdhcmRlZCBzaW5jZSAyMDIyLiBJdCBpbmNsdWRlcyBkYXRhIG9uIGFsbCBncmFudC1mdW5kZWQgY2VudGVycyBhY3Jvc3MgYWxsIE1CREEgcHJvZ3JhbXMsIHByb3ZpZGluZyBpbmZvcm1hdGlvbiBvbiBlYWNoIGdyYW50ZWXigJlzIGluY2x1ZGluZyBsb2NhdGlvbiwgY29udGFjdCBkZXRhaWxzLCBzZXJ2aWNlIGFyZWEsIGFuZCBpdHMgYXNzb2NpYXRlZCBNQkRBIHByb2dyYW0uJmx0O2JyJmd0OyZsdDticiZndDtBZGRpdGlvbmFsIGluZm9ybWF0aW9uIGluY2x1ZGVzIHRoZSBzdGF0dXMgb2YgZWFjaCBncmFudGVlICh3aGV0aGVyIHRoZXkgYXJlIGN1cnJlbnRseSBmdW5kZWQgYW5kIG9wZXJhdGluZyksIGdyYW50IGF3YXJkIGlkZW50aWZpZXJzLCBhbmQgYSBicmllZiBkZXNjcmlwdGlvbiBvZiB0aGUgZ3JhbnRlZXMgc2VydmljZXMgYW5kIHNwZWNpYWxpdGllcy4gRGV0YWlsZWQgaW5mb3JtYXRpb24gaXMgcHJvdmlkZWQgaW4gdGhlIGRhdGEgc2NoZW1hIHByb3ZpZGVkIGJlbG93LiZsdDticiZndDsmbHQ7c3BhbiZndDsmbHQ7YnImZ3Q7TUJEQeKAmXMgbWlzc2lvbiBpcyB0byBwcm9tb3RlIHRoZSBncm93dGggYW5kIGdsb2JhbCBjb21wZXRpdGl2ZW5lc3Mgb2YgTWlub3JpdHkgQnVzaW5lc3MgRW50ZXJwcmlzZXMgKE1CRSkgaW4gb3JkZXIgdG8gdW5sb2NrIHRoZSBjb3VudHJ54oCZcyBmdWxsIGVjb25vbWljIHBvdGVudGlhbC4gTUJEQSBwcm9ncmFtcyBwcm92aWRlIHN1cHBvcnQgZm9yIE1CRXMgdGhyb3VnaCBhIHZhcmlldHkgb2Ygc2VydmljZXMgYWltZWQgYXQgaW1wcm92aW5nIGFjY2VzcyB0byBjYXBpdGFsLCBjb250cmFjdHMsIGFuZCBtYXJrZXRzLiBUaGVzZSBwcm9ncmFtcyBoZWxwIGVudHJlcHJlbmV1cnMgb3ZlcmNvbWUgYmFycmllcnMgdG8gc3VjY2VzcyBhbmQgZXhwYW5kIHRoZWlyIGJ1c2luZXNzZXMgYnkgb2ZmZXJpbmcgdGFpbG9yZWQgdGVjaG5pY2FsIGFzc2lzdGFuY2UsIGJ1c2luZXNzIGNvbnN1bHRpbmcsIGFuZCBhY2Nlc3MgdG8gbmV0d29ya3MuJmx0O2JyJmd0OyZsdDticiZndDtOb3RlOiB0aGUgb3JpZ2luYWwgd2Vic2l0ZSBpcyB0aXRsZWQgMjAwMi0yMDI0IGdyYW50ZWVzIGJ1dCB0aGUgZGVzY3JpcHRpb24gcmVmZXJzIHRvIGdyYW50cyBhd2FyZGVkIHNpbmNlIDIwMjImbHQ7YnImZ3Q7Jmx0Oy9zcGFuJmd0OzwvZGVzY3JpcHRpb24+CiAgPC9kZXNjcmlwdGlvbnM+CiAgPGdlb0xvY2F0aW9ucz4KICAgIDxnZW9Mb2NhdGlvbj4KICAgICAgPGdlb0xvY2F0aW9uUGxhY2UgeG1sbnM6eHM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hIiB4c2k6dHlwZT0ieHM6c3RyaW5nIj5VLlMuIFRlcnJpdG9yaWVzPC9nZW9Mb2NhdGlvblBsYWNlPgogICAgPC9nZW9Mb2NhdGlvbj4KICAgIDxnZW9Mb2NhdGlvbj4KICAgICAgPGdlb0xvY2F0aW9uUGxhY2UgeG1sbnM6eHM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hIiB4c2k6dHlwZT0ieHM6c3RyaW5nIj5VLlMuIFN0YXRlczwvZ2VvTG9jYXRpb25QbGFjZT4KICAgIDwvZ2VvTG9jYXRpb24+CiAgPC9nZW9Mb2NhdGlvbnM+CjwvcmVzb3VyY2U+","url":"https://www.datalumos.org/datalumos/project/223443/version/V1/view","contentUrl":null,"metadataVersion":0,"schemaVersion":"http://datacite.org/schema/kernel-4","source":"api","isActive":true,"state":"findable","reason":null,"viewCount":0,"viewsOverTime":[],"downloadCount":0,"downloadsOverTime":[],"referenceCount":0,"citationCount":0,"citationsOverTime":[],"partCount":0,"partOfCount":0,"versionCount":0,"versionOfCount":1,"created":"2025-03-19T15:17:50.000Z","registered":"2025-03-19T15:17:50.000Z","published":"2025","updated":"2025-03-19T15:17:51.000Z"},"relationships":{"client":{"data":{"id":"gesis.icpsr","type":"clients"}},"provider":{"data":{"id":"icpsr","type":"providers"}},"media":{"data":{"id":"10.3886/e223443v1","type":"media"}},"references":{"data":[]},"citations":{"data":[]},"parts":{"data":[]},"partOf":{"data":[]},"versions":{"data":[]},"versionOf":{"data":[{"id":"10.3886/e223443","type":"dois"}]}}}}

Dois are correct, so fill in doi col with guesses

In [ ]:
df['doi'] = df['doi'].combine_first(df['doi_guess'])

## Getting DOIs from other archives

In [ ]:
missing_doi = df[df['doi'].isna()]

In [23]:
missing_doi.head(2)

,Unnamed: 0_x,file,schema,title,organization,agency,websites,data_source,description,last_modified,metadata_available,metadata_url,category,resource_count,Unnamed: 0_y,project_title,id,url,format,status,size,download_date,maintainer,notes,domain,doi,project_id,version,doi_guess
3,3,_datasets/2006-iur-public-database.md,data_rescue_project,2006 IUR Public Database,Environmental Protection Agency,Environmental Protection Agency,epa.gov,https://www.epa.gov/chemical-data-reporting/downloadable-2006-iur-public-database,NaN,2025-09-18,True,https://www.epa.gov/chemical-data-reporting/downloadable-2006-iur-public-database,Climate & Environment,1,3,2006 IUR Public Database,1280,https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi10.7910/DVN/F3A62W,"mhtml, ZIP, PDF",Finished,0.005,2025-02-26,"HD, CAFE-RCC","There was a 2006 version and a 2002-1986 version. Both are archived, hence 2 dataverse URLs. ~ag. Seperate Metadata https://www.epa.gov/chemical-data-reporting/summary-cdr-reporting-requirements-year, https://www.epa.gov/chemical-data-reporting/downloadable-2006-iur-public-database",dataverse.harvard.edu,None,NaN,NaN,None
62,62,_datasets/a-high-throughput-turbulent-mixing-condensation-aerosol-concentrator-for-direct-aerosol-collection-as-a-liquid-suspension.md,data_rescue_project,"A High-throughput, Turbulent-mixing, Condensation Aerosol Concentrator for Direct Aerosol Collection as a Liquid Suspension",Centers for Disease Control and Prevention (CDC),Department of Health and Human Services,data.cdc.gov,https://data.cdc.gov/National-Institute-for-Occupational-Safety-and-Hea/A-High-throughput-Turbulent-mixing-Condensation-Ae/c75w-3h6e,NaN,2025-11-05,False,NaN,Health & Healthcare,1,62,"A High-throughput, Turbulent-mixing, Condensation Aerosol Concentrator for Direct Aerosol Collection as a Liquid Suspension",1513,https://www.datalumos.org/datalumos/project/233571/view,NaN,Finished,NaN,NaN,DL,NaN,www.datalumos.org,None,NaN,NaN,None

In [24]:
missing_doi['domain'].value_counts()

domain
www.datalumos.org                                308
www.dropbox.com                                   85
sciop.net                                         72
dataverse.harvard.edu                             46
zenodo.org                                        34
archive.org                                       28
github.com                                        22
urban-data-catalog.s3.us-east-1.amazonaws.com     10
purl.stanford.edu                                 10
nlrbresearch.com                                   4
web.archive.org                                    3
arcgis.com                                         3
www.openicpsr.org                                  3
www.arcgis.com                                     3
biglocalnews.org                                   3
doi.pangaea.de                                     2
www.hydroshare.org                                 1
s3.amazonaws.com                                   1
tables.codeberg.page                               1
www.thelgbtqarchive.org                            1
box.hu-berlin.de                                   1
www.zelma.ai                                       1
www.documentcloud.org                              1
gofile.me                                          1
public.tableau.com                                 1
edgi-govdata-archiving.github.io                   1
erica.datarescueproject.org                        1
hub.arcgis.com                                     1
source.coop                                        1
livingatlas.arcgis.com                             1
data.openei.org                                    1
Name: count, dtype: int64

In [25]:
missing_doi['domain'].unique()

array(['dataverse.harvard.edu', 'www.datalumos.org', 'nlrbresearch.com',
       'urban-data-catalog.s3.us-east-1.amazonaws.com', 'www.dropbox.com',
       'sciop.net', 'livingatlas.arcgis.com', 'web.archive.org',
       'zenodo.org', 'archive.org', None, 'github.com',
       'purl.stanford.edu', 'source.coop', 'hub.arcgis.com',
       'doi.pangaea.de', 'www.zelma.ai', 'erica.datarescueproject.org',
       'edgi-govdata-archiving.github.io', 'public.tableau.com',
       'biglocalnews.org', 'gofile.me', 'www.documentcloud.org',
       's3.amazonaws.com', 'box.hu-berlin.de', 'www.arcgis.com',
       'www.openicpsr.org', 'arcgis.com', 'www.thelgbtqarchive.org',
       'tables.codeberg.page', 'www.hydroshare.org', 'data.openei.org'],
      dtype=object)

### urban-data-catalog.s3.us-east-1.amazonaws.com

In [26]:
missing_doi[missing_doi['domain'] == 'urban-data-catalog.s3.us-east-1.amazonaws.com'].head(2)

,Unnamed: 0_x,file,schema,title,organization,agency,websites,data_source,description,last_modified,metadata_available,metadata_url,category,resource_count,Unnamed: 0_y,project_title,id,url,format,status,size,download_date,maintainer,notes,domain,doi,project_id,version,doi_guess
99,99,_datasets/affirmatively-furthering-fair-housing-affh-data.md,data_rescue_project,Affirmatively Furthering Fair Housing (AFFH) Data,Department of Housing and Urban Development,Department of Housing and Urban Development,hud.gov,https://www.hud.gov/AFFH,NaN,2025-05-19,True,https://datacatalog.urban.org/dataset/us-department-housing-and-urban-development-affirmatively-furthering-fair-housing-hud-affh,Housing & Community Development,1,99,Affirmatively Furthering Fair Housing (AFFH) Data,1037,https://urban-data-catalog.s3.us-east-1.amazonaws.com/drupal-root-live/2025/04/03/housing-and-communities/hud-affh/data.zip,ZIP,Finished,0.876,2024-12-18,UI,"This dataset contains all data, documentation, and file resources linked to on the main US Department of Housing and Urban Development’s Affirmatively Furthering Fair Housing (AFFH) page and powering the AFFH tool.",urban-data-catalog.s3.us-east-1.amazonaws.com,None,NaN,NaN,None
103,103,_datasets/aging-independence-and-disability-agid-program-portal-data.md,data_rescue_project,"AGing, Independence, and Disability (AGID) Program Portal Data",Administration for Community Living,Department of Health and Human Services,agid.acl.gov,https://agid.acl.gov/release.html,NaN,2025-05-19,True,https://datacatalog.urban.org/dataset/aging-independence-and-disability-agid-program-portal-data,Health & Healthcare; Social Services,1,103,"AGing, Independence, and Disability (AGID) Program Portal Data",1041,https://urban-data-catalog.s3.us-east-1.amazonaws.com/drupal-root-live/2025/03/28/race-and-equity/agid/data.zip,ZIP,Finished,6.000,2025-03-28,UI,"This resource contains all data from AGing, Independence, and Disability’s Program Data Portal from the US Department of Health and Human Services’ Administration for Community Living.",urban-data-catalog.s3.us-east-1.amazonaws.com,None,NaN,NaN,None

not gonna work :(

### dataverse.harvard.edu

In [27]:
missing_doi[missing_doi['domain'] == 'dataverse.harvard.edu'].head(2)

,Unnamed: 0_x,file,schema,title,organization,agency,websites,data_source,description,last_modified,metadata_available,metadata_url,category,resource_count,Unnamed: 0_y,project_title,id,url,format,status,size,download_date,maintainer,notes,domain,doi,project_id,version,doi_guess
3,3,_datasets/2006-iur-public-database.md,data_rescue_project,2006 IUR Public Database,Environmental Protection Agency,Environmental Protection Agency,epa.gov,https://www.epa.gov/chemical-data-reporting/downloadable-2006-iur-public-database,NaN,2025-09-18,True,https://www.epa.gov/chemical-data-reporting/downloadable-2006-iur-public-database,Climate & Environment,1,3,2006 IUR Public Database,1280,https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi10.7910/DVN/F3A62W,"mhtml, ZIP, PDF",Finished,0.005,2025-02-26,"HD, CAFE-RCC","There was a 2006 version and a 2002-1986 version. Both are archived, hence 2 dataverse URLs. ~ag. Seperate Metadata https://www.epa.gov/chemical-data-reporting/summary-cdr-reporting-requirements-year, https://www.epa.gov/chemical-data-reporting/downloadable-2006-iur-public-database",dataverse.harvard.edu,None,NaN,NaN,None
196,189,_datasets/area-health-resource-files.md,data_rescue_project,Area Health Resource Files,Health Resources and Services Administration,Department of Health and Human Services,data.hrsa.gov,https://data.hrsa.gov/data/download,NaN,2025-02-17,True,NaN,Health & Healthcare,3,196,Area Health Resource Files,1267,https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi10.7910/DVN/MWNGDP,"ZIP, PDF, CSV, XLSX",Finished,0.183,2025-06-17,"HD, CAFE-RCC","The dataset exists in a dropdown menu on a webpage with other datasets. Suggest printing PDF of the full page for context, but uploading each section seperately.",dataverse.harvard.edu,None,NaN,NaN,None

In [28]:
is_harvard = (df['domain'].eq('dataverse.harvard.edu') & df['url'].notna())

df.loc[is_harvard, 'doi_guess'] = (
    df.loc[is_harvard, 'url']
      .astype(str)
      .str.extract(r'persistentId=([^&#]+)', expand=False)
      .apply(lambda x: unquote(x) if pd.notna(x) else pd.NA)
      .str.lower()
      .str.strip()
      .str.replace('doi:', '', regex=False)
      .str.replace('doi', '', regex=False)
)

df.loc[is_harvard, ['url', 'doi_guess']].head()

,url,doi_guess
3,https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi10.7910/DVN/F3A62W,10.7910/dvn/f3a62w
196,https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi10.7910/DVN/MWNGDP,10.7910/dvn/mwngdp
201,https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi10.7910/DVN/U7WVNO,10.7910/dvn/u7wvno
236,https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi%3A10.7910%2FDVN%2FFRAGKR,10.7910/dvn/fragkr
241,https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi10.7910/DVN/0L9K3E,10.7910/dvn/0l9k3e

In [ ]:
test = '10.7910/dvn/f3a62w'

url = f'https://api.datacite.org/dois/{test}'

headers = {
    'Accept': 'application/vnd.api+json'
}

response = requests.get(url, headers=headers)

print(response.text)

{"data":{"id":"10.7910/dvn/f3a62w","type":"dois","attributes":{"doi":"10.7910/dvn/f3a62w","prefix":"10.7910","suffix":"dvn/f3a62w","identifiers":[],"alternateIdentifiers":[],"creators":[{"name":"EPA","nameType":"Organizational","affiliation":["U.S. EPA"],"nameIdentifiers":[]}],"titles":[{"title":"Extracted Data From: Downloadable 2006 IUR Public Database"}],"publisher":"Harvard Dataverse","container":{},"publicationYear":2025,"subjects":[{"subject":"Chemistry"},{"subject":"Earth and Environmental Sciences"},{"subject":"Environmental Health","schemeUri":"https://tools.niehs.nih.gov/cchhglossary/"},{"subject":"Exposure"}],"contributors":[{"name":"CAFE","nameType":"Personal","affiliation":[],"contributorType":"ContactPerson","nameIdentifiers":[]}],"dates":[{"date":"2025-02-18","dateType":"Submitted"},{"date":"2025-02-26","dateType":"Available"},{"date":"2025-02-26","dateType":"Updated"},{"date":"2006-01-01/2006-12-31","dateType":"Other","dateInformation":"Time period covered by the data"},{"date":"2025","dateType":"Issued"}],"language":null,"types":{"ris":"DATA","bibtex":"misc","citeproc":"dataset","schemaOrg":"Dataset","resourceType":"Extracted Data","resourceTypeGeneral":"Dataset"},"relatedIdentifiers":[],"relatedItems":[],"sizes":["2211081","952281","1528334"],"formats":["application/pdf","multipart/related","application/zip"],"version":"1.0","rightsList":[{"rightsUri":"info:eu-repo/semantics/openAccess"},{"rights":"Creative Commons Attribution Non Commercial Share Alike 4.0 International","rightsUri":"https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode","schemeUri":"https://spdx.org/licenses/","rightsIdentifier":"cc-by-nc-sa-4.0","rightsIdentifierScheme":"SPDX"}],"descriptions":[{"description":"This submission includes publicly available data extracted in its original form. Please reference the Related Publication listed here for source and citation information \u0026lt;br /\u0026gt;\u0026lt;br /\u0026gt;\n\nThe following file contains information reported to EPA under the 2006 Inventory Update Rule (IUR). Please note that no information claimed as TSCA Confidential Business Information by an IUR reporter is contained in this file.\n[https://www.epa.gov/chemical-data-reporting/downloadable-2006-iur-public-database] \n\u0026lt;br /\u0026gt; \u0026lt;br /\u0026gt;\n\nIf you have questions about the underlying data stored here, please contact U.S. Environmental Protection Agency. TSCA-Hotline@epa.gov is said to answer questions on chemical data reporting requirements for the current version of the program that generated this historical data. It's unclear if they would have much information on this particular data set. But they might be able to redirect a query. If you have questions or recommendations related to this metadata entry and extracted data, please contact the CAFE Data Management team at: climatecafe@bu.edu.\n\u0026lt;br /\u0026gt;\u0026lt;br /\u0026gt;\n\nThis ACCDB [Access database] file is downloaded in compressed (ZIP) file format. After downloading the file to your preferred location, double-click on the file to extract the ACCDB file. This data requires the use of the database application program Microsoft Access [or, possibly, Microsoft SQL.","descriptionType":"Abstract"},{"description":"This submission includes publicly available data extracted in its original form. Please reference the Related Publication listed here for source and citation information.\n\nDownloadable 2006 IUR Public Database data was downloaded by Anne Gunn\non 2025-02-18","descriptionType":"Other"},{"description":"Microsoft Access, unknown","descriptionType":"TechnicalInfo"},{"description":"The disclaimers below were copied as is from the EPA Disclaimers site (https://www.epa.gov/web-policies-and-procedures/epa-disclaimers): \"Disclaimer of Endorsement Mention of or referral to commercial products or services, and/or links to non-EPA sites does not imply official EPA endorsement of or responsibility for the opinions, ideas, data, or products presented at those locations, or guarantee the validity of the information provided. Mention of commercial products/services on non-EPA websites is provided solely as a pointer to information on topics related to environmental protection that may be useful to EPA staff and the public. Copyright Status The U.S. Government retains a nonexclusive, royalty-free license to publish or reproduce these documents, or allow others to do so, for U.S. Government purposes. These documents may be freely distributed and used for non-commercial, scientific and educational purposes. Commercial use of the documents available from the EPA websites may be protected under the U.S. and Foreign Copyright Laws. Individual documents on the EPA website may have different copyright conditions, and that will be noted in those documents. Disclaimer of Liability With respect to documents available from the EPA website, neither the United States Government nor any of their employees, makes any warranty, express or implied, including the warranties of merchantability and fitness for a particular purpose, or assumes any legal liability or responsibility for the accuracy, completeness, or usefulness of any information, apparatus, product, or process disclosed, or represents that its use would not infringe privately owned rights. Exit Disclaimer The Exit icon denotes that you are leaving the EPA website and entering an external link or a third-party site. EPA's official web site is www.epa.gov. EPA has provided this link because it provides additional information that may be useful or interesting and is being provided in a manner consistent with the intended purpose of the EPA website. Please note that EPA uses third-party sites to provide EPA content already on www.epa.gov in a different format. EPA cannot attest to the accuracy of non-EPA information provided by these third-party sites or any other linked site. EPA is providing these links for your reference. In doing so, EPA does not endorse any non-government websites, companies or applications. Also, please be aware that the privacy protection provided on the EPA.gov domain (EPA Privacy and Security Notice) does not apply to these third-party sites. To learn more about EPA and social media, please refer to\u0026amp; our social media page. Notice Information from the EPA website resides on numerous computer systems funded by the Agency. The use of the EPA websites may be monitored for computer security purposes. Any unauthorized access to the EPA website is prohibited and is subject to criminal and civil penalties under federal laws including, but not limited to, Public Law 99-474, the Computer Fraud and Abuse Act of 1986. Terms of Use for Geospatial Data These geospatial data and corresponding cartographic materials have been approved for use by the U.S. Environmental Protection Agency (EPA) as advised by the EPA Geospatial Advisory Committee (EGAC). This approved release is on the condition that neither the EPA nor the U.S. Government may be held liable for any damages resulting from its authorized or unauthorized use. These data and any corresponding products, services, or materials do not necessarily represent the EPA’s official position or viewpoint, expressed or implied. These content items are not intended for use in establishing liability or calculating cost recovery statutes of limitations. They cannot be relied upon to create any rights, substantive or procedural, enforceable by any party in litigation with the United States or third parties. Additionally, although these data have been processed successfully on EPA computer systems, no warranty expressed or implied can be made regarding the accuracy or utility of the data on any other system or for general or scientific purposes, nor shall the act of distribution constitute any such warranty. The Agency reserves the right to revise EPA-stewarded datasets pursuant to further analysis and review without public notice. Unless otherwise specified, geospatial data produced by the EPA is by default in the public domain and is not subject to domestic copyright protection under 17 U.S.C. § 105. Referenced data from non-EPA sources are neither inherently verified nor independently tested by the Agency in all circumstances. Permission to reproduce copyrighted items not produced by the EPA must be secured from the copyright owner. EPA strongly recommends careful attention be paid to metadata files associated with these data to better understand limitations, restrictions or intended use. The U.S. EPA shall not be held liable for improper or incorrect use of the data.\"","descriptionType":"Methods"}],"geoLocations":[],"fundingReferences":[],"xml":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHJlc291cmNlIHhtbG5zPSJodHRwOi8vZGF0YWNpdGUub3JnL3NjaGVtYS9rZXJuZWwtNCIgeG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeHNpOnNjaGVtYUxvY2F0aW9uPSJodHRwOi8vZGF0YWNpdGUub3JnL3NjaGVtYS9rZXJuZWwtNCBodHRwOi8vc2NoZW1hLmRhdGFjaXRlLm9yZy9tZXRhL2tlcm5lbC00LjUvbWV0YWRhdGEueHNkIj4KICA8aWRlbnRpZmllciBpZGVudGlmaWVyVHlwZT0iRE9JIj4xMC43OTEwL0RWTi9GM0E2Mlc8L2lkZW50aWZpZXI+CiAgPGNyZWF0b3JzPgogICAgPGNyZWF0b3I+CiAgICAgIDxjcmVhdG9yTmFtZSBuYW1lVHlwZT0iT3JnYW5pemF0aW9uYWwiPkVQQTwvY3JlYXRvck5hbWU+CiAgICAgIDxhZmZpbGlhdGlvbj5VLlMuIEVQQTwvYWZmaWxpYXRpb24+CiAgICA8L2NyZWF0b3I+CiAgPC9jcmVhdG9ycz4KICA8dGl0bGVzPgogICAgPHRpdGxlPkV4dHJhY3RlZCBEYXRhIEZyb206IERvd25sb2FkYWJsZSAyMDA2IElVUiBQdWJsaWMgRGF0YWJhc2U8L3RpdGxlPgogIDwvdGl0bGVzPgogIDxwdWJsaXNoZXI+SGFydmFyZCBEYXRhdmVyc2U8L3B1Ymxpc2hlcj4KICA8cHVibGljYXRpb25ZZWFyPjIwMjU8L3B1YmxpY2F0aW9uWWVhcj4KICA8c3ViamVjdHM+CiAgICA8c3ViamVjdD5DaGVtaXN0cnk8L3N1YmplY3Q+CiAgICA8c3ViamVjdD5FYXJ0aCBhbmQgRW52aXJvbm1lbnRhbCBTY2llbmNlczwvc3ViamVjdD4KICAgIDxzdWJqZWN0IHNjaGVtZVVSST0iaHR0cHM6Ly90b29scy5uaWVocy5uaWguZ292L2NjaGhnbG9zc2FyeS8iPkVudmlyb25tZW50YWwgSGVhbHRoPC9zdWJqZWN0PgogICAgPHN1YmplY3Q+RXhwb3N1cmU8L3N1YmplY3Q+CiAgPC9zdWJqZWN0cz4KICA8Y29udHJpYnV0b3JzPgogICAgPGNvbnRyaWJ1dG9yIGNvbnRyaWJ1dG9yVHlwZT0iQ29udGFjdFBlcnNvbiI+CiAgICAgIDxjb250cmlidXRvck5hbWUgbmFtZVR5cGU9IlBlcnNvbmFsIj5DQUZFPC9jb250cmlidXRvck5hbWU+CiAgICA8L2NvbnRyaWJ1dG9yPgogIDwvY29udHJpYnV0b3JzPgogIDxkYXRlcz4KICAgIDxkYXRlIGRhdGVUeXBlPSJTdWJtaXR0ZWQiPjIwMjUtMDItMTg8L2RhdGU+CiAgICA8ZGF0ZSBkYXRlVHlwZT0iQXZhaWxhYmxlIj4yMDI1LTAyLTI2PC9kYXRlPgogICAgPGRhdGUgZGF0ZVR5cGU9IlVwZGF0ZWQiPjIwMjUtMDItMjY8L2RhdGU+CiAgICA8ZGF0ZSBkYXRlVHlwZT0iT3RoZXIiIGRhdGVJbmZvcm1hdGlvbj0iVGltZSBwZXJpb2QgY292ZXJlZCBieSB0aGUgZGF0YSI+MjAwNi0wMS0wMS8yMDA2LTEyLTMxPC9kYXRlPgogIDwvZGF0ZXM+CiAgPHJlc291cmNlVHlwZSByZXNvdXJjZVR5cGVHZW5lcmFsPSJEYXRhc2V0Ij5FeHRyYWN0ZWQgRGF0YTwvcmVzb3VyY2VUeXBlPgogIDxzaXplcz4KICAgIDxzaXplPjIyMTEwODE8L3NpemU+CiAgICA8c2l6ZT45NTIyODE8L3NpemU+CiAgICA8c2l6ZT4xNTI4MzM0PC9zaXplPgogIDwvc2l6ZXM+CiAgPGZvcm1hdHM+CiAgICA8Zm9ybWF0PmFwcGxpY2F0aW9uL3BkZjwvZm9ybWF0PgogICAgPGZvcm1hdD5tdWx0aXBhcnQvcmVsYXRlZDwvZm9ybWF0PgogICAgPGZvcm1hdD5hcHBsaWNhdGlvbi96aXA8L2Zvcm1hdD4KICA8L2Zvcm1hdHM+CiAgPHZlcnNpb24+MS4wPC92ZXJzaW9uPgogIDxyaWdodHNMaXN0PgogICAgPHJpZ2h0cyByaWdodHNVUkk9ImluZm86ZXUtcmVwby9zZW1hbnRpY3Mvb3BlbkFjY2VzcyIvPgogICAgPHJpZ2h0cyByaWdodHNVUkk9Imh0dHA6Ly9jcmVhdGl2ZWNvbW1vbnMub3JnL2xpY2Vuc2VzL2J5LW5jLXNhLzQuMCI+Q0MgQlktTkMtU0EgNC4wPC9yaWdodHM+CiAgPC9yaWdodHNMaXN0PgogIDxkZXNjcmlwdGlvbnM+CiAgICA8ZGVzY3JpcHRpb24gZGVzY3JpcHRpb25UeXBlPSJBYnN0cmFjdCI+VGhpcyBzdWJtaXNzaW9uIGluY2x1ZGVzIHB1YmxpY2x5IGF2YWlsYWJsZSBkYXRhIGV4dHJhY3RlZCBpbiBpdHMgb3JpZ2luYWwgZm9ybS4gUGxlYXNlIHJlZmVyZW5jZSB0aGUgUmVsYXRlZCBQdWJsaWNhdGlvbiBsaXN0ZWQgaGVyZSBmb3Igc291cmNlIGFuZCBjaXRhdGlvbiBpbmZvcm1hdGlvbiAmYW1wO2x0O2JyIC8mYW1wO2d0OyZhbXA7bHQ7YnIgLyZhbXA7Z3Q7CgpUaGUgZm9sbG93aW5nIGZpbGUgY29udGFpbnMgaW5mb3JtYXRpb24gcmVwb3J0ZWQgdG8gRVBBIHVuZGVyIHRoZSAyMDA2IEludmVudG9yeSBVcGRhdGUgUnVsZSAoSVVSKS4gUGxlYXNlIG5vdGUgdGhhdCBubyBpbmZvcm1hdGlvbiBjbGFpbWVkIGFzIFRTQ0EgQ29uZmlkZW50aWFsIEJ1c2luZXNzIEluZm9ybWF0aW9uIGJ5IGFuIElVUiByZXBvcnRlciBpcyBjb250YWluZWQgaW4gdGhpcyBmaWxlLgpbaHR0cHM6Ly93d3cuZXBhLmdvdi9jaGVtaWNhbC1kYXRhLXJlcG9ydGluZy9kb3dubG9hZGFibGUtMjAwNi1pdXItcHVibGljLWRhdGFiYXNlXSAKJmFtcDtsdDticiAvJmFtcDtndDsgJmFtcDtsdDticiAvJmFtcDtndDsKCklmIHlvdSBoYXZlIHF1ZXN0aW9ucyBhYm91dCB0aGUgdW5kZXJseWluZyBkYXRhIHN0b3JlZCBoZXJlLCBwbGVhc2UgY29udGFjdCBVLlMuIEVudmlyb25tZW50YWwgUHJvdGVjdGlvbiBBZ2VuY3kuIFRTQ0EtSG90bGluZUBlcGEuZ292IGlzIHNhaWQgdG8gYW5zd2VyIHF1ZXN0aW9ucyBvbiBjaGVtaWNhbCBkYXRhIHJlcG9ydGluZyByZXF1aXJlbWVudHMgZm9yIHRoZSBjdXJyZW50IHZlcnNpb24gb2YgdGhlIHByb2dyYW0gdGhhdCBnZW5lcmF0ZWQgdGhpcyBoaXN0b3JpY2FsIGRhdGEuIEl0JmFtcDthcG9zO3MgdW5jbGVhciBpZiB0aGV5IHdvdWxkIGhhdmUgbXVjaCBpbmZvcm1hdGlvbiBvbiB0aGlzIHBhcnRpY3VsYXIgZGF0YSBzZXQuIEJ1dCB0aGV5IG1pZ2h0IGJlIGFibGUgdG8gcmVkaXJlY3QgYSBxdWVyeS4gSWYgeW91IGhhdmUgcXVlc3Rpb25zIG9yIHJlY29tbWVuZGF0aW9ucyByZWxhdGVkIHRvIHRoaXMgbWV0YWRhdGEgZW50cnkgYW5kIGV4dHJhY3RlZCBkYXRhLCBwbGVhc2UgY29udGFjdCB0aGUgQ0FGRSBEYXRhIE1hbmFnZW1lbnQgdGVhbSBhdDogY2xpbWF0ZWNhZmVAYnUuZWR1LgomYW1wO2x0O2JyIC8mYW1wO2d0OyZhbXA7bHQ7YnIgLyZhbXA7Z3Q7CgpUaGlzIEFDQ0RCIFtBY2Nlc3MgZGF0YWJhc2VdIGZpbGUgaXMgZG93bmxvYWRlZCBpbiBjb21wcmVzc2VkIChaSVApIGZpbGUgZm9ybWF0LiBBZnRlciBkb3dubG9hZGluZyB0aGUgZmlsZSB0byB5b3VyIHByZWZlcnJlZCBsb2NhdGlvbiwgZG91YmxlLWNsaWNrIG9uIHRoZSBmaWxlIHRvIGV4dHJhY3QgdGhlIEFDQ0RCIGZpbGUuIFRoaXMgZGF0YSByZXF1aXJlcyB0aGUgdXNlIG9mIHRoZSBkYXRhYmFzZSBhcHBsaWNhdGlvbiBwcm9ncmFtIE1pY3Jvc29mdCBBY2Nlc3MgW29yLCBwb3NzaWJseSwgTWljcm9zb2Z0IFNRTC48L2Rlc2NyaXB0aW9uPgogICAgPGRlc2NyaXB0aW9uIGRlc2NyaXB0aW9uVHlwZT0iT3RoZXIiPlRoaXMgc3VibWlzc2lvbiBpbmNsdWRlcyBwdWJsaWNseSBhdmFpbGFibGUgZGF0YSBleHRyYWN0ZWQgaW4gaXRzIG9yaWdpbmFsIGZvcm0uIFBsZWFzZSByZWZlcmVuY2UgdGhlIFJlbGF0ZWQgUHVibGljYXRpb24gbGlzdGVkIGhlcmUgZm9yIHNvdXJjZSBhbmQgY2l0YXRpb24gaW5mb3JtYXRpb24uCgpEb3dubG9hZGFibGUgMjAwNiBJVVIgUHVibGljIERhdGFiYXNlIGRhdGEgd2FzIGRvd25sb2FkZWQgYnkgQW5uZSBHdW5uCm9uIDIwMjUtMDItMTg8L2Rlc2NyaXB0aW9uPgogICAgPGRlc2NyaXB0aW9uIGRlc2NyaXB0aW9uVHlwZT0iVGVjaG5pY2FsSW5mbyI+TWljcm9zb2Z0IEFjY2VzcywgdW5rbm93bjwvZGVzY3JpcHRpb24+CiAgICA8ZGVzY3JpcHRpb24gZGVzY3JpcHRpb25UeXBlPSJNZXRob2RzIj5UaGUgZGlzY2xhaW1lcnMgYmVsb3cgd2VyZSBjb3BpZWQgYXMgaXMgZnJvbSB0aGUgRVBBIERpc2NsYWltZXJzIHNpdGUgKGh0dHBzOi8vd3d3LmVwYS5nb3Yvd2ViLXBvbGljaWVzLWFuZC1wcm9jZWR1cmVzL2VwYS1kaXNjbGFpbWVycyk6ICJEaXNjbGFpbWVyIG9mIEVuZG9yc2VtZW50IE1lbnRpb24gb2Ygb3IgcmVmZXJyYWwgdG8gY29tbWVyY2lhbCBwcm9kdWN0cyBvciBzZXJ2aWNlcywgYW5kL29yIGxpbmtzIHRvIG5vbi1FUEEgc2l0ZXMgZG9lcyBub3QgaW1wbHkgb2ZmaWNpYWwgRVBBIGVuZG9yc2VtZW50IG9mIG9yIHJlc3BvbnNpYmlsaXR5IGZvciB0aGUgb3BpbmlvbnMsIGlkZWFzLCBkYXRhLCBvciBwcm9kdWN0cyBwcmVzZW50ZWQgYXQgdGhvc2UgbG9jYXRpb25zLCBvciBndWFyYW50ZWUgdGhlIHZhbGlkaXR5IG9mIHRoZSBpbmZvcm1hdGlvbiBwcm92aWRlZC4gTWVudGlvbiBvZiBjb21tZXJjaWFsIHByb2R1Y3RzL3NlcnZpY2VzIG9uIG5vbi1FUEEgd2Vic2l0ZXMgaXMgcHJvdmlkZWQgc29sZWx5IGFzIGEgcG9pbnRlciB0byBpbmZvcm1hdGlvbiBvbiB0b3BpY3MgcmVsYXRlZCB0byBlbnZpcm9ubWVudGFsIHByb3RlY3Rpb24gdGhhdCBtYXkgYmUgdXNlZnVsIHRvIEVQQSBzdGFmZiBhbmQgdGhlIHB1YmxpYy4gQ29weXJpZ2h0IFN0YXR1cyBUaGUgVS5TLiBHb3Zlcm5tZW50IHJldGFpbnMgYSBub25leGNsdXNpdmUsIHJveWFsdHktZnJlZSBsaWNlbnNlIHRvIHB1Ymxpc2ggb3IgcmVwcm9kdWNlIHRoZXNlIGRvY3VtZW50cywgb3IgYWxsb3cgb3RoZXJzIHRvIGRvIHNvLCBmb3IgVS5TLiBHb3Zlcm5tZW50IHB1cnBvc2VzLiBUaGVzZSBkb2N1bWVudHMgbWF5IGJlIGZyZWVseSBkaXN0cmlidXRlZCBhbmQgdXNlZCBmb3Igbm9uLWNvbW1lcmNpYWwsIHNjaWVudGlmaWMgYW5kIGVkdWNhdGlvbmFsIHB1cnBvc2VzLiBDb21tZXJjaWFsIHVzZSBvZiB0aGUgZG9jdW1lbnRzIGF2YWlsYWJsZSBmcm9tIHRoZSBFUEEgd2Vic2l0ZXMgbWF5IGJlIHByb3RlY3RlZCB1bmRlciB0aGUgVS5TLiBhbmQgRm9yZWlnbiBDb3B5cmlnaHQgTGF3cy4gSW5kaXZpZHVhbCBkb2N1bWVudHMgb24gdGhlIEVQQSB3ZWJzaXRlIG1heSBoYXZlIGRpZmZlcmVudCBjb3B5cmlnaHQgY29uZGl0aW9ucywgYW5kIHRoYXQgd2lsbCBiZSBub3RlZCBpbiB0aG9zZSBkb2N1bWVudHMuIERpc2NsYWltZXIgb2YgTGlhYmlsaXR5IFdpdGggcmVzcGVjdCB0byBkb2N1bWVudHMgYXZhaWxhYmxlIGZyb20gdGhlIEVQQSB3ZWJzaXRlLCBuZWl0aGVyIHRoZSBVbml0ZWQgU3RhdGVzIEdvdmVybm1lbnQgbm9yIGFueSBvZiB0aGVpciBlbXBsb3llZXMsIG1ha2VzIGFueSB3YXJyYW50eSwgZXhwcmVzcyBvciBpbXBsaWVkLCBpbmNsdWRpbmcgdGhlIHdhcnJhbnRpZXMgb2YgbWVyY2hhbnRhYmlsaXR5IGFuZCBmaXRuZXNzIGZvciBhIHBhcnRpY3VsYXIgcHVycG9zZSwgb3IgYXNzdW1lcyBhbnkgbGVnYWwgbGlhYmlsaXR5IG9yIHJlc3BvbnNpYmlsaXR5IGZvciB0aGUgYWNjdXJhY3ksIGNvbXBsZXRlbmVzcywgb3IgdXNlZnVsbmVzcyBvZiBhbnkgaW5mb3JtYXRpb24sIGFwcGFyYXR1cywgcHJvZHVjdCwgb3IgcHJvY2VzcyBkaXNjbG9zZWQsIG9yIHJlcHJlc2VudHMgdGhhdCBpdHMgdXNlIHdvdWxkIG5vdCBpbmZyaW5nZSBwcml2YXRlbHkgb3duZWQgcmlnaHRzLiBFeGl0IERpc2NsYWltZXIgVGhlIEV4aXQgaWNvbiBkZW5vdGVzIHRoYXQgeW91IGFyZSBsZWF2aW5nIHRoZSBFUEEgd2Vic2l0ZSBhbmQgZW50ZXJpbmcgYW4gZXh0ZXJuYWwgbGluayBvciBhIHRoaXJkLXBhcnR5IHNpdGUuIEVQQSdzIG9mZmljaWFsIHdlYiBzaXRlIGlzIHd3dy5lcGEuZ292LiBFUEEgaGFzIHByb3ZpZGVkIHRoaXMgbGluayBiZWNhdXNlIGl0IHByb3ZpZGVzIGFkZGl0aW9uYWwgaW5mb3JtYXRpb24gdGhhdCBtYXkgYmUgdXNlZnVsIG9yIGludGVyZXN0aW5nIGFuZCBpcyBiZWluZyBwcm92aWRlZCBpbiBhIG1hbm5lciBjb25zaXN0ZW50IHdpdGggdGhlIGludGVuZGVkIHB1cnBvc2Ugb2YgdGhlIEVQQSB3ZWJzaXRlLiBQbGVhc2Ugbm90ZSB0aGF0IEVQQSB1c2VzIHRoaXJkLXBhcnR5IHNpdGVzIHRvIHByb3ZpZGUgRVBBIGNvbnRlbnQgYWxyZWFkeSBvbiB3d3cuZXBhLmdvdiBpbiBhIGRpZmZlcmVudCBmb3JtYXQuIEVQQSBjYW5ub3QgYXR0ZXN0IHRvIHRoZSBhY2N1cmFjeSBvZiBub24tRVBBIGluZm9ybWF0aW9uIHByb3ZpZGVkIGJ5IHRoZXNlIHRoaXJkLXBhcnR5IHNpdGVzIG9yIGFueSBvdGhlciBsaW5rZWQgc2l0ZS4gRVBBIGlzIHByb3ZpZGluZyB0aGVzZSBsaW5rcyBmb3IgeW91ciByZWZlcmVuY2UuIEluIGRvaW5nIHNvLCBFUEEgZG9lcyBub3QgZW5kb3JzZSBhbnkgbm9uLWdvdmVybm1lbnQgd2Vic2l0ZXMsIGNvbXBhbmllcyBvciBhcHBsaWNhdGlvbnMuIEFsc28sIHBsZWFzZSBiZSBhd2FyZSB0aGF0IHRoZSBwcml2YWN5IHByb3RlY3Rpb24gcHJvdmlkZWQgb24gdGhlIEVQQS5nb3YgZG9tYWluIChFUEEgUHJpdmFjeSBhbmQgU2VjdXJpdHkgTm90aWNlKSBkb2VzIG5vdCBhcHBseSB0byB0aGVzZSB0aGlyZC1wYXJ0eSBzaXRlcy4gVG8gbGVhcm4gbW9yZSBhYm91dCBFUEEgYW5kIHNvY2lhbCBtZWRpYSwgcGxlYXNlIHJlZmVyIHRvJmFtcDsgb3VyIHNvY2lhbCBtZWRpYSBwYWdlLiBOb3RpY2UgSW5mb3JtYXRpb24gZnJvbSB0aGUgRVBBIHdlYnNpdGUgcmVzaWRlcyBvbiBudW1lcm91cyBjb21wdXRlciBzeXN0ZW1zIGZ1bmRlZCBieSB0aGUgQWdlbmN5LiBUaGUgdXNlIG9mIHRoZSBFUEEgd2Vic2l0ZXMgbWF5IGJlIG1vbml0b3JlZCBmb3IgY29tcHV0ZXIgc2VjdXJpdHkgcHVycG9zZXMuIEFueSB1bmF1dGhvcml6ZWQgYWNjZXNzIHRvIHRoZSBFUEEgd2Vic2l0ZSBpcyBwcm9oaWJpdGVkIGFuZCBpcyBzdWJqZWN0IHRvIGNyaW1pbmFsIGFuZCBjaXZpbCBwZW5hbHRpZXMgdW5kZXIgZmVkZXJhbCBsYXdzIGluY2x1ZGluZywgYnV0IG5vdCBsaW1pdGVkIHRvLCBQdWJsaWMgTGF3IDk5LTQ3NCwgdGhlIENvbXB1dGVyIEZyYXVkIGFuZCBBYnVzZSBBY3Qgb2YgMTk4Ni4gVGVybXMgb2YgVXNlIGZvciBHZW9zcGF0aWFsIERhdGEgVGhlc2UgZ2Vvc3BhdGlhbCBkYXRhIGFuZCBjb3JyZXNwb25kaW5nIGNhcnRvZ3JhcGhpYyBtYXRlcmlhbHMgaGF2ZSBiZWVuIGFwcHJvdmVkIGZvciB1c2UgYnkgdGhlIFUuUy4gRW52aXJvbm1lbnRhbCBQcm90ZWN0aW9uIEFnZW5jeSAoRVBBKSBhcyBhZHZpc2VkIGJ5IHRoZSBFUEEgR2Vvc3BhdGlhbCBBZHZpc29yeSBDb21taXR0ZWUgKEVHQUMpLiBUaGlzIGFwcHJvdmVkIHJlbGVhc2UgaXMgb24gdGhlIGNvbmRpdGlvbiB0aGF0IG5laXRoZXIgdGhlIEVQQSBub3IgdGhlIFUuUy4gR292ZXJubWVudCBtYXkgYmUgaGVsZCBsaWFibGUgZm9yIGFueSBkYW1hZ2VzIHJlc3VsdGluZyBmcm9tIGl0cyBhdXRob3JpemVkIG9yIHVuYXV0aG9yaXplZCB1c2UuIFRoZXNlIGRhdGEgYW5kIGFueSBjb3JyZXNwb25kaW5nIHByb2R1Y3RzLCBzZXJ2aWNlcywgb3IgbWF0ZXJpYWxzIGRvIG5vdCBuZWNlc3NhcmlseSByZXByZXNlbnQgdGhlIEVQQeKAmXMgb2ZmaWNpYWwgcG9zaXRpb24gb3Igdmlld3BvaW50LCBleHByZXNzZWQgb3IgaW1wbGllZC4gVGhlc2UgY29udGVudCBpdGVtcyBhcmUgbm90IGludGVuZGVkIGZvciB1c2UgaW4gZXN0YWJsaXNoaW5nIGxpYWJpbGl0eSBvciBjYWxjdWxhdGluZyBjb3N0IHJlY292ZXJ5IHN0YXR1dGVzIG9mIGxpbWl0YXRpb25zLiBUaGV5IGNhbm5vdCBiZSByZWxpZWQgdXBvbiB0byBjcmVhdGUgYW55IHJpZ2h0cywgc3Vic3RhbnRpdmUgb3IgcHJvY2VkdXJhbCwgZW5mb3JjZWFibGUgYnkgYW55IHBhcnR5IGluIGxpdGlnYXRpb24gd2l0aCB0aGUgVW5pdGVkIFN0YXRlcyBvciB0aGlyZCBwYXJ0aWVzLiBBZGRpdGlvbmFsbHksIGFsdGhvdWdoIHRoZXNlIGRhdGEgaGF2ZSBiZWVuIHByb2Nlc3NlZCBzdWNjZXNzZnVsbHkgb24gRVBBIGNvbXB1dGVyIHN5c3RlbXMsIG5vIHdhcnJhbnR5IGV4cHJlc3NlZCBvciBpbXBsaWVkIGNhbiBiZSBtYWRlIHJlZ2FyZGluZyB0aGUgYWNjdXJhY3kgb3IgdXRpbGl0eSBvZiB0aGUgZGF0YSBvbiBhbnkgb3RoZXIgc3lzdGVtIG9yIGZvciBnZW5lcmFsIG9yIHNjaWVudGlmaWMgcHVycG9zZXMsIG5vciBzaGFsbCB0aGUgYWN0IG9mIGRpc3RyaWJ1dGlvbiBjb25zdGl0dXRlIGFueSBzdWNoIHdhcnJhbnR5LiBUaGUgQWdlbmN5IHJlc2VydmVzIHRoZSByaWdodCB0byByZXZpc2UgRVBBLXN0ZXdhcmRlZCBkYXRhc2V0cyBwdXJzdWFudCB0byBmdXJ0aGVyIGFuYWx5c2lzIGFuZCByZXZpZXcgd2l0aG91dCBwdWJsaWMgbm90aWNlLiBVbmxlc3Mgb3RoZXJ3aXNlIHNwZWNpZmllZCwgZ2Vvc3BhdGlhbCBkYXRhIHByb2R1Y2VkIGJ5IHRoZSBFUEEgaXMgYnkgZGVmYXVsdCBpbiB0aGUgcHVibGljIGRvbWFpbiBhbmQgaXMgbm90IHN1YmplY3QgdG8gZG9tZXN0aWMgY29weXJpZ2h0IHByb3RlY3Rpb24gdW5kZXIgMTcgVS5TLkMuIMKnIDEwNS4gUmVmZXJlbmNlZCBkYXRhIGZyb20gbm9uLUVQQSBzb3VyY2VzIGFyZSBuZWl0aGVyIGluaGVyZW50bHkgdmVyaWZpZWQgbm9yIGluZGVwZW5kZW5

In [ ]:
df['doi'] = df['doi'].fillna(df['doi_guess'])

### zenodo.org

In [31]:
missing_doi[missing_doi['domain'] == 'zenodo.org'].head(2)

,Unnamed: 0_x,file,schema,title,organization,agency,websites,data_source,description,last_modified,metadata_available,metadata_url,category,resource_count,Unnamed: 0_y,project_title,id,url,format,status,size,download_date,maintainer,notes,domain,doi,project_id,version,doi_guess
173,172,_datasets/annual-energy-outlook.md,data_rescue_project,Annual Energy Outlook,US Department of Energy - Office of the CIO,Department of Energy,eia.gov,https://www.eia.gov/outlooks/aeo/data/browser/,NaN,2025-02-12,False,NaN,Energy,1,173,Annual Energy Outlook,73,https://zenodo.org/records/10838488,"XLSX, ZIP",Finished,6.7,2025-03-19,"PEDP, CaCo",NaN,zenodo.org,None,NaN,NaN,None
177,176,_datasets/annual-technology-baseline-atb-for-electricity-and-transportation.md,data_rescue_project,Annual Technology Baseline (ATB) for Electricity and Transportation,National Renewable Energy Laboratory,Department of Energy,nrel.gov,https://atb.nrel.gov/,NaN,2025-03-23,False,NaN,Energy; Climate & Environment,1,177,Annual Technology Baseline (ATB) for Electricity and Transportation,234,https://zenodo.org/records/14784563,"Parquet, XLSX, JSON",Finished,3.7,2024-08-01,"PEDP, CaCo",NaN,zenodo.org,None,NaN,NaN,None

In [32]:
is_zenodo = (df['domain'].eq('zenodo.org') & df['url'].notna())

df.loc[is_zenodo, 'doi_guess'] = (
    df.loc[is_zenodo, 'url']
      .astype(str)
      .str.extract(r'/records?/(\d+)', expand=False)
      .apply(lambda x: f'10.5281/zenodo.{x}' if pd.notna(x) else pd.NA)
      .str.lower()
)

df.loc[is_zenodo, ['url', 'doi_guess']].head()

                                     url                doi_guess
173  https://zenodo.org/records/10838488  10.5281/zenodo.10838488
177  https://zenodo.org/records/14784563  10.5281/zenodo.14784563
335  https://zenodo.org/records/15047648  10.5281/zenodo.15047648
336  https://zenodo.org/records/15047486  10.5281/zenodo.15047486
337  https://zenodo.org/records/15047671  10.5281/zenodo.15047671

In [33]:
test = '10.5281/zenodo.10838488'
url = f'https://api.datacite.org/dois/{test}'
headers = {'Accept': 'application/vnd.api+json'}
response = requests.get(url, headers=headers)

print(response.text)

{"data":{"id":"10.5281/zenodo.10838488","type":"dois","attributes":{"doi":"10.5281/zenodo.10838488","prefix":"10.5281","suffix":"zenodo.10838488","identifiers":[{"identifier":"oai:zenodo.org:10838488","identifierType":"oai"}],"alternateIdentifiers":[{"alternateIdentifierType":"oai","alternateIdentifier":"oai:zenodo.org:10838488"}],"creators":[{"name":"Catalyst Cooperative","nameType":"Personal","familyName":"Catalyst Cooperative","affiliation":["Catalyst Cooperative"],"nameIdentifiers":[]}],"titles":[{"title":"PUDL Raw EIA Annual Energy Outlook (AEO)"}],"publisher":"Zenodo","container":{},"publicationYear":2024,"subjects":[{"subject":"MW"},{"subject":"MWh"},{"subject":"annual energy outlook"},{"subject":"distribution"},{"subject":"eia"},{"subject":"eia aeo"},{"subject":"electric"},{"subject":"electricity"},{"subject":"energy"},{"subject":"energy consumption"},{"subject":"energy information administration"},{"subject":"energy supply"},{"subject":"federal"},{"subject":"fuel projections"},{"subject":"generation"},{"subject":"government"},{"subject":"kW"},{"subject":"kWh"},{"subject":"kilowatt hours"},{"subject":"kilowatts"},{"subject":"megawatt hours"},{"subject":"megawatts"},{"subject":"nems"},{"subject":"power"},{"subject":"transmission"},{"subject":"united states"},{"subject":"us"},{"subject":"usa"},{"subject":"utility"}],"contributors":[],"dates":[{"date":"2024-03-19","dateType":"Issued"}],"language":"en","types":{"ris":"DATA","bibtex":"misc","citeproc":"dataset","schemaOrg":"Dataset","resourceType":"","resourceTypeGeneral":"Dataset"},"relatedIdentifiers":[{"relationType":"IsVersionOf","relatedIdentifier":"10.5281/zenodo.10838487","relatedIdentifierType":"DOI"}],"relatedItems":[],"sizes":[],"formats":[],"version":"1.0.0","rightsList":[{"rights":"Other (Public Domain)","rightsIdentifier":"other-pd","rightsIdentifierScheme":""}],"descriptions":[{"description":"The EIA Annual Energy Outlook provides projections of future fuel prices, energy supply and consumption, and carbon dioxide emissions by sector and region. Archived from \nhttps://www.eia.gov/outlooks/aeo/\n\nThis archive contains raw input data for the Public Utility Data Liberation (PUDL)\nsoftware developed by Catalyst Cooperative. It is\norganized into Frictionless\nData Packages. For additional information about this data and PUDL, see the\nfollowing resources:\n\n\n  \nThe PUDL Repository on GitHub\n  \nPUDL Documentation\n  \nOther Catalyst Cooperative data archives","descriptionType":"Abstract"}],"geoLocations":[],"fundingReferences":[],"xml":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHJlc291cmNlIHhtbG5zOnhzaT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEtaW5zdGFuY2UiIHhtbG5zPSJodHRwOi8vZGF0YWNpdGUub3JnL3NjaGVtYS9rZXJuZWwtNCIgeHNpOnNjaGVtYUxvY2F0aW9uPSJodHRwOi8vZGF0YWNpdGUub3JnL3NjaGVtYS9rZXJuZWwtNCBodHRwOi8vc2NoZW1hLmRhdGFjaXRlLm9yZy9tZXRhL2tlcm5lbC00L21ldGFkYXRhLnhzZCI+CiAgPGlkZW50aWZpZXIgaWRlbnRpZmllclR5cGU9IkRPSSI+MTAuNTI4MS9aRU5PRE8uMTA4Mzg0ODg8L2lkZW50aWZpZXI+CiAgPGNyZWF0b3JzPgogICAgPGNyZWF0b3I+CiAgICAgIDxjcmVhdG9yTmFtZSBuYW1lVHlwZT0iUGVyc29uYWwiPkNhdGFseXN0IENvb3BlcmF0aXZlPC9jcmVhdG9yTmFtZT4KICAgICAgPGZhbWlseU5hbWU+Q2F0YWx5c3QgQ29vcGVyYXRpdmU8L2ZhbWlseU5hbWU+CiAgICAgIDxhZmZpbGlhdGlvbj5DYXRhbHlzdCBDb29wZXJhdGl2ZTwvYWZmaWxpYXRpb24+CiAgICA8L2NyZWF0b3I+CiAgPC9jcmVhdG9ycz4KICA8dGl0bGVzPgogICAgPHRpdGxlPlBVREwgUmF3IEVJQSBBbm51YWwgRW5lcmd5IE91dGxvb2sgKEFFTyk8L3RpdGxlPgogIDwvdGl0bGVzPgogIDxwdWJsaXNoZXI+WmVub2RvPC9wdWJsaXNoZXI+CiAgPHB1YmxpY2F0aW9uWWVhcj4yMDI0PC9wdWJsaWNhdGlvblllYXI+CiAgPHJlc291cmNlVHlwZSByZXNvdXJjZVR5cGVHZW5lcmFsPSJEYXRhc2V0Ii8+CiAgPHN1YmplY3RzPgogICAgPHN1YmplY3Q+TVc8L3N1YmplY3Q+CiAgICA8c3ViamVjdD5NV2g8L3N1YmplY3Q+CiAgICA8c3ViamVjdD5hbm51YWwgZW5lcmd5IG91dGxvb2s8L3N1YmplY3Q+CiAgICA8c3ViamVjdD5kaXN0cmlidXRpb248L3N1YmplY3Q+CiAgICA8c3ViamVjdD5laWE8L3N1YmplY3Q+CiAgICA8c3ViamVjdD5laWEgYWVvPC9zdWJqZWN0PgogICAgPHN1YmplY3Q+ZWxlY3RyaWM8L3N1YmplY3Q+CiAgICA8c3ViamVjdD5lbGVjdHJpY2l0eTwvc3ViamVjdD4KICAgIDxzdWJqZWN0PmVuZXJneTwvc3ViamVjdD4KICAgIDxzdWJqZWN0PmVuZXJneSBjb25zdW1wdGlvbjwvc3ViamVjdD4KICAgIDxzdWJqZWN0PmVuZXJneSBpbmZvcm1hdGlvbiBhZG1pbmlzdHJhdGlvbjwvc3ViamVjdD4KICAgIDxzdWJqZWN0PmVuZXJneSBzdXBwbHk8L3N1YmplY3Q+CiAgICA8c3ViamVjdD5mZWRlcmFsPC9zdWJqZWN0PgogICAgPHN1YmplY3Q+ZnVlbCBwcm9qZWN0aW9uczwvc3ViamVjdD4KICAgIDxzdWJqZWN0PmdlbmVyYXRpb248L3N1YmplY3Q+CiAgICA8c3ViamVjdD5nb3Zlcm5tZW50PC9zdWJqZWN0PgogICAgPHN1YmplY3Q+a1c8L3N1YmplY3Q+CiAgICA8c3ViamVjdD5rV2g8L3N1YmplY3Q+CiAgICA8c3ViamVjdD5raWxvd2F0dCBob3Vyczwvc3ViamVjdD4KICAgIDxzdWJqZWN0PmtpbG93YXR0czwvc3ViamVjdD4KICAgIDxzdWJqZWN0Pm1lZ2F3YXR0IGhvdXJzPC9zdWJqZWN0PgogICAgPHN1YmplY3Q+bWVnYXdhdHRzPC9zdWJqZWN0PgogICAgPHN1YmplY3Q+bmVtczwvc3ViamVjdD4KICAgIDxzdWJqZWN0PnBvd2VyPC9zdWJqZWN0PgogICAgPHN1YmplY3Q+dHJhbnNtaXNzaW9uPC9zdWJqZWN0PgogICAgPHN1YmplY3Q+dW5pdGVkIHN0YXRlczwvc3ViamVjdD4KICAgIDxzdWJqZWN0PnVzPC9zdWJqZWN0PgogICAgPHN1YmplY3Q+dXNhPC9zdWJqZWN0PgogICAgPHN1YmplY3Q+dXRpbGl0eTwvc3ViamVjdD4KICA8L3N1YmplY3RzPgogIDxkYXRlcz4KICAgIDxkYXRlIGRhdGVUeXBlPSJJc3N1ZWQiPjIwMjQtMDMtMTk8L2RhdGU+CiAgPC9kYXRlcz4KICA8bGFuZ3VhZ2U+ZW5nPC9sYW5ndWFnZT4KICA8YWx0ZXJuYXRlSWRlbnRpZmllcnM+CiAgICA8YWx0ZXJuYXRlSWRlbnRpZmllciBhbHRlcm5hdGVJZGVudGlmaWVyVHlwZT0ib2FpIj5vYWk6emVub2RvLm9yZzoxMDgzODQ4ODwvYWx0ZXJuYXRlSWRlbnRpZmllcj4KICA8L2FsdGVybmF0ZUlkZW50aWZpZXJzPgogIDxyZWxhdGVkSWRlbnRpZmllcnM+CiAgICA8cmVsYXRlZElkZW50aWZpZXIgcmVsYXRlZElkZW50aWZpZXJUeXBlPSJET0kiIHJlbGF0aW9uVHlwZT0iSXNWZXJzaW9uT2YiPjEwLjUyODEvemVub2RvLjEwODM4NDg3PC9yZWxhdGVkSWRlbnRpZmllcj4KICA8L3JlbGF0ZWRJZGVudGlmaWVycz4KICA8c2l6ZXMvPgogIDxmb3JtYXRzLz4KICA8dmVyc2lvbj4xLjAuMDwvdmVyc2lvbj4KICA8cmlnaHRzTGlzdD4KICAgIDxyaWdodHMgcmlnaHRzSWRlbnRpZmllcj0ib3RoZXItcGQiIHJpZ2h0c0lkZW50aWZpZXJTY2hlbWU9IiI+T3RoZXIgKFB1YmxpYyBEb21haW4pPC9yaWdodHM+CiAgPC9yaWdodHNMaXN0PgogIDxkZXNjcmlwdGlvbnM+CiAgICA8ZGVzY3JpcHRpb24gZGVzY3JpcHRpb25UeXBlPSJBYnN0cmFjdCI+VGhlIEVJQSBBbm51YWwgRW5lcmd5IE91dGxvb2sgcHJvdmlkZXMgcHJvamVjdGlvbnMgb2YgZnV0dXJlIGZ1ZWwgcHJpY2VzLCBlbmVyZ3kgc3VwcGx5IGFuZCBjb25zdW1wdGlvbiwgYW5kIGNhcmJvbiBkaW94aWRlIGVtaXNzaW9ucyBieSBzZWN0b3IgYW5kIHJlZ2lvbi4gQXJjaGl2ZWQgZnJvbSAKaHR0cHM6Ly93d3cuZWlhLmdvdi9vdXRsb29rcy9hZW8vCgpUaGlzIGFyY2hpdmUgY29udGFpbnMgcmF3IGlucHV0IGRhdGEgZm9yIHRoZSBQdWJsaWMgVXRpbGl0eSBEYXRhIExpYmVyYXRpb24gKFBVREwpCnNvZnR3YXJlIGRldmVsb3BlZCBieSBDYXRhbHlzdCBDb29wZXJhdGl2ZS4gSXQgaXMKb3JnYW5pemVkIGludG8gRnJpY3Rpb25sZXNzCkRhdGEgUGFja2FnZXMuIEZvciBhZGRpdGlvbmFsIGluZm9ybWF0aW9uIGFib3V0IHRoaXMgZGF0YSBhbmQgUFVETCwgc2VlIHRoZQpmb2xsb3dpbmcgcmVzb3VyY2VzOgoKCiAgClRoZSBQVURMIFJlcG9zaXRvcnkgb24gR2l0SHViCiAgClBVREwgRG9jdW1lbnRhdGlvbgogIApPdGhlciBDYXRhbHlzdCBDb29wZXJhdGl2ZSBkYXRhIGFyY2hpdmVzPC9kZXNjcmlwdGlvbj4KICA8L2Rlc2NyaXB0aW9ucz4KPC9yZXNvdXJjZT4K","url":"https://zenodo.org/doi/10.5281/zenodo.10838488","contentUrl":null,"metadataVersion":0,"schemaVersion":"http://datacite.org/schema/kernel-4","source":"api","isActive":true,"state":"findable","reason":null,"viewCount":0,"viewsOverTime":[],"downloadCount":0,"downloadsOverTime":[],"referenceCount":0,"citationCount":0,"citationsOverTime":[],"partCount":0,"partOfCount":0,"versionCount":0,"versionOfCount":1,"created":"2024-03-19T13:00:25.000Z","registered":"2024-03-19T13:00:25.000Z","published":"2024","updated":"2025-05-12T15:46:57.000Z"},"relationships":{"client":{"data":{"id":"cern.zenodo","type":"clients"}},"provider":{"data":{"id":"cern","type":"providers"}},"media":{"data":{"id":"10.5281/zenodo.10838488","type":"media"}},"references":{"data":[]},"citations":{"data":[]},"parts":{"data":[]},"partOf":{"data":[]},"versions":{"data":[]},"versionOf":{"data":[{"id":"10.5281/zenodo.10838487","type":"dois"}]}}}}

In [ ]:
df['doi'] = df['doi'].fillna(df['doi_guess'])

Filling in DOIs with no version

In [ ]:
# grab project id
df['project_id'] = df['url'].astype(str).str.extract(r'/project/(\d+)', expand=False)

# grab version if present, otherwise default to V1 for datalumos project links
df['version'] = df['url'].astype(str).str.extract(r'/version/(V\d+)', expand=False)

mask_datalumos = df['domain'].isin(['www.datalumos.org', 'datalumos.org']) & df['project_id'].notna()
df.loc[mask_datalumos & df['version'].isna(), 'version'] = 'V1'

# build DOI guess for datalumos rows where we have project_id + version
mask_guess = mask_datalumos & df['version'].notna()
df.loc[mask_guess, 'doi_guess'] = (
    '10.3886/E' + df.loc[mask_guess, 'project_id'] + df.loc[mask_guess, 'version']
)

df['doi'] = df['doi'].fillna(df['doi_guess'])

df.loc[mask_datalumos, ['url', 'project_id', 'version', 'doi_guess', 'doi']]

,url,project_id,version,doi_guess,doi
1,https://www.datalumos.org/datalumos/project/243434/version/V1/view,243434,V1,10.3886/E243434V1,10.3886/E243434V1
2,https://www.datalumos.org/datalumos/project/223443/version/V1/view,223443,V1,10.3886/E223443V1,10.3886/E223443V1
4,https://www.datalumos.org/datalumos/project/244041/version/V1/view,244041,V1,10.3886/E244041V1,10.3886/E244041V1
5,https://www.datalumos.org/datalumos/project/222881/version/V1/view,222881,V1,10.3886/E222881V1,10.3886/E222881V1
6,https://www.datalumos.org/datalumos/project/222043/version/V1/view,222043,V1,10.3886/E222043V1,10.3886/E222043V1
...,...,...,...,...,...
3016,https://www.datalumos.org/datalumos/project/223063/version/V1/view,223063,V1,10.3886/E223063V1,10.3886/E223063V1
3017,https://www.datalumos.org/datalumos/project/220761/view,220761,V1,10.3886/E220761V1,10.3886/E220761V1
3020,https://www.datalumos.org/datalumos/project/242851/version/V1/view,242851,V1,10.3886/E242851V1,10.3886/E242851V1
3021,https://www.datalumos.org/datalumos/project/244042/version/V1/view,244042,V1,10.3886/E244042V1,10.3886/E244042V1
3022,https://www.datalumos.org/datalumos/project/237626/view,237626,V1,10.3886/E237626V1,10.3886/E237626V1

## Getting metadata through DataCite API

### Making sure we don't make unnecessary duplicate calls

In [ ]:
dois = df['doi'].dropna().astype(str).str.strip().str.lower().unique()
dois

array(['10.3886/e226824v1', '10.3886/e243434v1', '10.3886/e223443v1', ...,
       '10.3886/e242851v1', '10.3886/e244042v1', '10.3886/e237626v1'],
      dtype=object)

In [ ]:
unique_dois = (
    df['doi']
    .dropna()
    .astype(str)
    .str.strip()
    .str.lower()
    .unique()
)

len(unique_dois)

2396

Let's see some duplicates

In [ ]:
dup_rows = df[df['doi'].duplicated(keep=False)]
dup_rows[['doi', 'url', 'domain', 'title']].head(20)

,doi,url,domain,title
6,10.3886/E222043V1,https://www.datalumos.org/datalumos/project/222043/version/V1/view,www.datalumos.org,2016 AmeriCorps MES AmeriCorps Member Exit Survey
7,10.3886/E222044V2,https://www.datalumos.org/datalumos/project/222044/version/V2/view,www.datalumos.org,2017-2023 CEV Findings National Rates of All Measures by Demographics from the Current Population Survey Civic Engagement and Volunteering Supplement
8,10.3886/E222044V2,https://www.datalumos.org/datalumos/project/222044/version/V2/view,www.datalumos.org,2017-2023 CEV Findings National Rates of All Measures from the Current Population Survey Civic Engagement and Volunteering Supplement
9,10.3886/E222044V2,https://www.datalumos.org/datalumos/project/222044/version/V2/view,www.datalumos.org,2017-2023 CEV Findings State-Level Rates of All Measures from the Current Population Survey Civic Engagement and Volunteering Supplement
10,10.3886/E222043V1,https://www.datalumos.org/datalumos/project/222043/version/V1/view,www.datalumos.org,2017 AmeriCorps MES AmeriCorps Member Exit Survey
12,10.3886/E222044V2,https://www.datalumos.org/datalumos/project/222044/version/V2/view,www.datalumos.org,2017 CEV Data Current Population Survey Civic Engagement and Volunteering Supplement
13,10.3886/E222043V1,https://www.datalumos.org/datalumos/project/222043/version/V1/view,www.datalumos.org,2018 AmeriCorps MES AmeriCorps Member Exit Survey
17,10.3886/E222043V1,https://www.datalumos.org/datalumos/project/222043/version/V1/view,www.datalumos.org,2019 AmeriCorps MES AmeriCorps Member Exit Survey
18,10.3886/E224361V1,https://www.datalumos.org/datalumos/project/224361/version/V1/view,www.datalumos.org,2019 CDFI Program Awardee Performance Data Snapshot
19,10.3886/E222044V2,https://www.datalumos.org/datalumos/project/222044/version/V2/view,www.datalumos.org,2019 CEV Data Current Population Survey Civic Engagement and Volunteering Supplement
22,10.3886/E222043V1,https://www.datalumos.org/datalumos/project/222043/version/V1/view,www.datalumos.org,2020 AmeriCorps MES AmeriCorps Member Exit Survey
29,10.3886/E222043V1,https://www.datalumos.org/datalumos/project/222043/version/V1/view,www.datalumos.org,2021 AmeriCorps MES AmeriCorps Member Exit Survey
31,10.3886/E222044V2,https://www.datalumos.org/datalumos/project/222044/version/V2/view,www.datalumos.org,2021 CEV Data Current Population Survey Civic Engagement and Volunteering Supplement
37,10.3886/E222043V1,https://www.datalumos.org/datalumos/project/222043/version/V1/view,www.datalumos.org,2022 AmeriCorps MES AmeriCorps Member Exit Survey
39,10.3886/E223063V1,https://www.datalumos.org/datalumos/project/223063/version/V1/view,www.datalumos.org,2022 COVID-19 Workplace Safety Framework/Re-entry Plan
46,10.3886/E222043V1,https://www.datalumos.org/datalumos/project/222043/version/V1/view,www.datalumos.org,2023 AmeriCorps MES AmeriCorps Member Exit Survey
47,10.3886/E222044V2,https://www.datalumos.org/datalumos/project/222044/version/V2/view,www.datalumos.org,2023 CEV Data Current Population Survey Civic Engagement and Volunteering Supplement
81,None,https://nlrbresearch.com/NLRB/NLRB_DB?_search=type%3A+%22ALJ%22,nlrbresearch.com,Administrative Law Judge Decisions
99,None,https://urban-data-catalog.s3.us-east-1.amazonaws.com/drupal-root-live/2025/04/03/housing-and-communities/hud-affh/data.zip,urban-data-catalog.s3.us-east-1.amazonaws.com,Affirmatively Furthering Fair Housing (AFFH) Data
103,None,https://urban-data-catalog.s3.us-east-1.amazonaws.com/drupal-root-live/2025/03/28/race-and-equity/agid/data.zip,urban-data-catalog.s3.us-east-1.amazonaws.com,"AGing, Independence, and Disability (AGID) Program Portal Data"

In [39]:
df['doi'].value_counts()

doi
10.3886/E222581V1    51
10.3886/E223141V1    48
10.3886/E229201V1    37
10.3886/E223001V1    30
10.3886/E224621V1    25
                     ..
10.3886/E239395V1     1
10.3886/E239397V1     1
10.3886/E239789V1     1
10.3886/E239405V1     1
10.3886/E237626V1     1
Name: count, Length: 2397, dtype: int64

In [40]:
df[df['doi'] == '10.3886/E222581V1']

,Unnamed: 0_x,file,schema,title,organization,agency,websites,data_source,description,last_modified,metadata_available,metadata_url,category,resource_count,Unnamed: 0_y,project_title,id,url,format,status,size,download_date,maintainer,notes,domain,doi,project_id,version,doi_guess
1497,1453,_datasets/medical-expenditure-panel-survey-meps-topics.md,data_rescue_project,Medical Expenditure Panel Survey (MEPS) Topics,Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1497,Medical Expenditure Panel Survey (MEPS) Topics,447,https://www.datalumos.org/datalumos/project/222581/version/V1/view,"TSV, ZIP",Finished,0.243,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1516,1473,_datasets/meps-topics-access-to-health-care.md,data_rescue_project,MEPS Topics Access to Health Care,Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=1Z-1,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1516,MEPS Topics Access to Health Care,448,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1517,1474,_datasets/meps-topics-childrens-health.md,data_rescue_project,MEPS Topics Children's Health,Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=2Z-1,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1517,MEPS Topics Children's Health,449,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1518,1475,_datasets/meps-topics-childrens-insurance-coverage.md,data_rescue_project,MEPS Topics Children's Insurance Coverage,Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=3Z-1,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1518,MEPS Topics Children's Insurance Coverage,450,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1519,1476,_datasets/meps-topics-dental-visitsuseevents-and-expenditures.md,data_rescue_project,MEPS Topics Dental Visits/Use/Events and Expenditures,Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=47Z-1,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1519,MEPS Topics Dental Visits/Use/Events and Expenditures,451,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1520,1477,_datasets/meps-topics-disability.md,data_rescue_project,MEPS Topics Disability,Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=20Z-1,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1520,MEPS Topics Disability,452,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1521,1478,_datasets/meps-topics-doctor-visitsuseevents-and-expenditures.md,data_rescue_project,MEPS Topics Doctor Visits/Use/Events and Expenditures,Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=21Z-1,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1521,MEPS Topics Doctor Visits/Use/Events and Expenditures,453,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1522,1479,_datasets/meps-topics-doctors-separately-billing.md,data_rescue_project,"MEPS Topics Doctors, Separately Billing",Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=22Z-1,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1522,"MEPS Topics Doctors, Separately Billing",454,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1523,1480,_datasets/meps-topics-elderly-health-care.md,data_rescue_project,MEPS Topics Elderly Health Care,Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=8Z-1,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1523,MEPS Topics Elderly Health Care,455,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1524,1481,_datasets/meps-topics-emergency-room-visitsuseevents-and-expenditures.md,data_rescue_project,MEPS Topics Emergency Room Visits/Use/Events and Expenditures,Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=23Z-1,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1524,MEPS Topics Emergency Room Visits/Use/Events and Expenditures,456,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1525,1482,_datasets/meps-topics-employment-status.md,data_rescue_project,MEPS Topics Employment Status,Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=24Z-1,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1525,MEPS Topics Employment Status,457,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1526,1483,_datasets/meps-topics-health-care-disparities.md,data_rescue_project,MEPS Topics Health Care Disparities,Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=6Z-1,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1526,MEPS Topics Health Care Disparities,458,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1527,1484,_datasets/meps-topics-health-insurance-coverage.md,data_rescue_project,MEPS Topics Health Insurance Coverage,Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=7Z-1,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1527,MEPS Topics Health Insurance Coverage,459,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1528,1485,_datasets/meps-topics-health-insurance-employer-sponsored.md,data_rescue_project,MEPS Topics Health Insurance Employer-sponsored,Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=7Z2,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1528,MEPS Topics Health Insurance Employer-sponsored,460,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1529,1486,_datasets/meps-topics-health-insurance-individually-purchased.md,data_rescue_project,MEPS Topics Health Insurance Individually Purchased,Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=7Z3,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1529,MEPS Topics Health Insurance Individually Purchased,461,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1530,1487,_datasets/meps-topics-health-status.md,data_rescue_project,MEPS Topics Health Status,Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=26Z-1,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1530,MEPS Topics Health Status,462,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1531,1488,_datasets/meps-topics-home-health-care.md,data_rescue_project,MEPS Topics Home Health Care,Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=28Z-1,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1531,MEPS Topics Home Health Care,463,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1532,1489,_datasets/meps-topics-injuries.md,data_rescue_project,MEPS Topics Injuries,Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=30Z-1,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1532,MEPS Topics Injuries,464,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1533,1490,_datasets/meps-topics-jobs.md,data_rescue_project,MEPS Topics Jobs,Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=31Z-1,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1533,MEPS Topics Jobs,465,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1534,1491,_datasets/meps-topics-medical-conditions.md,data_rescue_project,MEPS Topics Medical Conditions,Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=32Z-1,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1534,MEPS Topics Medical Conditions,466,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1535,1492,_datasets/meps-topics-medical-providers-visitsuseevents-and-expenditures.md,data_rescue_project,MEPS Topics Medical Providers Visits/Use/Events and Expenditures,Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=34Z-1,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1535,MEPS Topics Medical Providers Visits/Use/Events and Expenditures,467,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1536,1493,_datasets/meps-topics-medicaremedicaidschip.md,data_rescue_project,MEPS Topics Medicare/Medicaid/SCHIP,Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=9Z-1,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1536,MEPS Topics Medicare/Medicaid/SCHIP,468,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1537,1494,_datasets/meps-topics-mens-health.md,data_rescue_project,MEPS Topics Men's Health,Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=35Z-1,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1537,MEPS Topics Men's Health,469,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1538,1495,_datasets/meps-topics-mental-health.md,data_rescue_project,MEPS Topics Mental Health,Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=11Z-1,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1538,MEPS Topics Mental Health,470,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1539,1496,_datasets/meps-topics-methodological-research.md,data_rescue_project,MEPS Topics Methodological Research,Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=49Z-1,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1539,MEPS Topics Methodological Research,471,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1540,1497,_datasets/meps-topics-minority-health.md,data_rescue_project,MEPS Topics Minority Health,Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=12Z-1,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1540,MEPS Topics Minority Health,472,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1541,1498,_datasets/meps-topics-obesity.md,data_rescue_project,MEPS Topics Obesity,Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=13Z-1,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1541,MEPS Topics Obesity,473,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1542,1499,_datasets/meps-topics-office-based-visitsuseevents-and-expenditures.md,data_rescue_project,MEPS Topics Office-Based Visits/Use/Events and Expenditures,Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=36Z-1,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1542,MEPS Topics Office-Based Visits/Use/Events and Expenditures,474,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1543,1500,_datasets/meps-topics-opioids.md,data_rescue_project,MEPS Topics Opioids,Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=50Z-1,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1543,MEPS Topics Opioids,475,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1544,1501,_datasets/meps-topics-pharmacies.md,data_rescue_project,MEPS Topics Pharmacies,Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=39Z-1,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1544,MEPS Topics Pharmacies,476,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1545,1502,_datasets/meps-topics-physicians-separately-billing.md,data_rescue_project,"MEPS Topics Physicians, Separately Billing",Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=40Z-1,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1545,"MEPS Topics Physicians, Separately Billing",477,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1546,1503,_datasets/meps-topics-prescription-drugs.md,data_rescue_project,MEPS Topics Prescription Drugs,Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=14Z-1,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1546,MEPS Topics Prescription Drugs,478,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1547,1504,_datasets/meps-topics-preventive-care.md,data_rescue_project,MEPS Topics Preventive Care,Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=42Z-1,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1547,MEPS Topics Preventive Care,479,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1548,1505,_datasets/meps-topics-priority-conditions----arthritis.md,data_rescue_project,MEPS Topics Priority Conditions -- Arthritis,Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=4Z5,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1548,MEPS Topics Priority Conditions -- Arthritis,480,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1
1549,1506,_datasets/meps-topics-priority-conditions----asthma.md,data_rescue_project,MEPS Topics Priority Conditions -- Asthma,Agency for Healthcare Research and Quality,Department of Health and Human Services,meps.ahrq.gov,https://meps.ahrq.gov/mepsweb/data_stats/MEPS_topics.jsp?topicid=4Z4,NaN,2025-03-18,False,NaN,Health & Healthcare,1,1549,MEPS Topics Priority Conditions -- Asthma,481,https://www.datalumos.org/datalumos/project/222581/version/V1/view,PDF,Finished,0.000,2025-03-03,"DRP, DL",NaN,www.datalumos.org,10.3886/E222581V1,222581,V1,10.3886/E222581V1

### Metadata

In [ ]:
MAILTO = 'maja.murawka@student.uva.nl'
session = requests.Session()
session.headers.update({
    'Accept': 'application/vnd.api+json',
    'User-Agent': f'metadata-harvest/1.0 (mailto:{MAILTO})'
})


rows = []
for doi in unique_dois:
    url = f'https://api.datacite.org/dois/{doi}'
    try:
        r = session.get(url, timeout=30)

        if r.status_code == 429:
            time.sleep(2)
            r = session.get(url, timeout=30)

        if r.status_code != 200:
            rows.append({'doi': doi, 'dc_ok': False, 'dc_status': r.status_code, 'dc_error': r.text[:200]})
            continue

        data = r.json()
        attrs = data.get('data', {}).get('attributes', {})
        rel = data.get('data', {}).get('relationships', {})

        row = {
            'doi': doi,
            'dc_ok': True,
            'dc_status': 200,
            'dc_raw': data,
        }

        for k in [
            'prefix', 'suffix', 'publisher', 'publicationYear', 'language',
            'version', 'url', 'contentUrl', 'schemaVersion', 'source',
            'isActive', 'state', 'reason', 'metadataVersion',
            'created', 'registered', 'published', 'updated',
            'viewCount', 'downloadCount', 'referenceCount', 'citationCount',
            'partCount', 'partOfCount', 'versionCount', 'versionOfCount'
        ]:
            row[f'dc_{k}'] = attrs.get(k)

        types = attrs.get('types') or {}
        row['dc_types_ris'] = types.get('ris')
        row['dc_types_bibtex'] = types.get('bibtex')
        row['dc_types_citeproc'] = types.get('citeproc')
        row['dc_types_schemaOrg'] = types.get('schemaOrg')
        row['dc_types_resourceTypeGeneral'] = types.get('resourceTypeGeneral')

        row['dc_identifiers'] = attrs.get('identifiers')
        row['dc_alternateIdentifiers'] = attrs.get('alternateIdentifiers')

        titles = attrs.get('titles') or []
        row['dc_title'] = titles[0].get('title') if titles else None
        row['dc_titles_all'] = titles

        creators = attrs.get('creators') or []
        row['dc_creators_all'] = creators
        row['dc_creators_names'] = '; '.join([c.get('name','') for c in creators if c.get('name')]) or None
        row['dc_creators_types'] = '; '.join([c.get('nameType','') for c in creators if c.get('nameType')]) or None

        # contributors
        contributors = attrs.get('contributors') or []
        row['dc_contributors_all'] = contributors
        row['dc_contributors_names'] = '; '.join([c.get('name','') for c in contributors if c.get('name')]) or None

        # subjects
        subjects = attrs.get('subjects') or []
        row['dc_subjects_all'] = subjects
        row['dc_subjects'] = '; '.join([s.get('subject','') for s in subjects if s.get('subject')]) or None

        # dates
        dates = attrs.get('dates') or []
        row['dc_dates_all'] = dates
        collected = [d.get('date') for d in dates if (d.get('dateType') or '').lower() == 'collected']
        issued = [d.get('date') for d in dates if (d.get('dateType') or '').lower() == 'issued']
        row['dc_date_collected'] = collected[0] if collected else None
        row['dc_date_issued'] = issued[0] if issued else None

        # descriptions
        descs = attrs.get('descriptions') or []
        row['dc_descriptions_all'] = descs
        abstract = [d.get('description') for d in descs if (d.get('descriptionType') or '').lower() == 'abstract']
        row['dc_abstract'] = abstract[0] if abstract else None

        # geolocations
        geos = attrs.get('geoLocations') or []
        row['dc_geoLocations_all'] = geos
        row['dc_geo_places'] = '; '.join(
            [g.get('geoLocationPlace','') for g in geos if g.get('geoLocationPlace')]
        ) or None

        # rights & funding
        row['dc_rightsList'] = attrs.get('rightsList')
        row['dc_fundingReferences'] = attrs.get('fundingReferences')

        # related identifiers
        relids = attrs.get('relatedIdentifiers') or []
        row['dc_relatedIdentifiers_all'] = relids
        row['dc_isVersionOf'] = '; '.join(
            [x.get('relatedIdentifier','') for x in relids if (x.get('relationType') or '') == 'IsVersionOf']
        ) or None

        # relationships (structured links)
        # e.g. provider/client/versionOf ids
        def rel_id(name):
            d = rel.get(name, {}).get('data')
            if isinstance(d, dict):
                return d.get('id')
            if isinstance(d, list):
                return '; '.join([x.get('id','') for x in d if isinstance(x, dict) and x.get('id')]) or None
            return None

        row['dc_rel_client'] = rel_id('client')
        row['dc_rel_provider'] = rel_id('provider')
        row['dc_rel_media'] = rel_id('media')
        row['dc_rel_versionOf'] = rel_id('versionOf')
        row['dc_rel_versions'] = rel_id('versions')
        row['dc_rel_parts'] = rel_id('parts')
        row['dc_rel_partOf'] = rel_id('partOf')
        row['dc_rel_citations'] = rel_id('citations')
        row['dc_rel_references'] = rel_id('references')

        rows.append(row)

    except Exception as e:
        rows.append({'doi': doi, 'dc_ok': False, 'dc_status': None, 'dc_error': str(e)})

datacite_df = pd.DataFrame(rows)
datacite_df.head(2)

KeyboardInterrupt:

In [ ]:
df['doi_norm'] = (
    df['doi']
    .astype(str)
    .str.strip()
    .str.lower()
    .replace({'nan': None, 'none': None, '': None})
)

datacite_df['doi_norm'] = (
    datacite_df['doi']
    .astype(str)
    .str.strip()
    .str.lower()
)

df = df.merge(
    datacite_df.drop(columns=['doi'], errors='ignore'),
    on='doi_norm',
    how='left'
)

In [ ]:
df = df.drop(columns='dc_raw')

In [ ]:
no_doi = df[df['doi'].isna()]

no_doi.head(2)

,file,schema,title,organization,agency,websites,data_source,description,last_modified,metadata_available,metadata_url,category,resource_count,project_title,id,url,format,status,size,download_date,maintainer,notes,domain,doi,project_id,version,doi_guess,doi_norm,dc_ok_x,dc_status_x,dc_prefix_x,dc_suffix_x,dc_publisher_x,dc_publicationYear_x,dc_language_x,dc_version_x,dc_url_x,dc_contentUrl_x,dc_schemaVersion_x,dc_source_x,dc_isActive_x,dc_state_x,dc_reason_x,dc_metadataVersion_x,dc_created_x,dc_registered_x,dc_published_x,dc_updated_x,dc_viewCount_x,dc_downloadCount_x,dc_referenceCount_x,dc_citationCount_x,dc_partCount_x,dc_partOfCount_x,dc_versionCount_x,dc_versionOfCount_x,dc_types_ris_x,dc_types_bibtex_x,dc_types_citeproc_x,dc_types_schemaOrg_x,dc_types_resourceTypeGeneral_x,dc_identifiers_x,dc_alternateIdentifiers_x,dc_title_x,dc_titles_all_x,dc_creators_all_x,dc_creators_names_x,dc_creators_types_x,dc_contributors_all_x,dc_contributors_names_x,dc_subjects_all_x,dc_subjects_x,dc_dates_all_x,dc_date_collected_x,dc_date_issued_x,dc_descriptions_all_x,dc_abstract_x,dc_geoLocations_all_x,dc_geo_places_x,dc_rightsList_x,dc_fundingReferences_x,dc_relatedIdentifiers_all_x,dc_isVersionOf_x,dc_rel_client_x,dc_rel_provider_x,dc_rel_media_x,dc_rel_versionOf_x,dc_rel_versions_x,dc_rel_parts_x,dc_rel_partOf_x,dc_rel_citations_x,dc_rel_references_x,dc_error_x,dc_ok_y,dc_status_y,dc_prefix_y,dc_suffix_y,dc_publisher_y,dc_publicationYear_y,dc_language_y,dc_version_y,dc_url_y,dc_contentUrl_y,dc_schemaVersion_y,dc_source_y,dc_isActive_y,dc_state_y,dc_reason_y,dc_metadataVersion_y,dc_created_y,dc_registered_y,dc_published_y,dc_updated_y,dc_viewCount_y,dc_downloadCount_y,dc_referenceCount_y,dc_citationCount_y,dc_partCount_y,dc_partOfCount_y,dc_versionCount_y,dc_versionOfCount_y,dc_types_ris_y,dc_types_bibtex_y,dc_types_citeproc_y,dc_types_schemaOrg_y,dc_types_resourceTypeGeneral_y,dc_identifiers_y,dc_alternateIdentifiers_y,dc_title_y,dc_titles_all_y,dc_creators_all_y,dc_creators_names_y,dc_creators_types_y,dc_contributors_all_y,dc_contributors_names_y,dc_subjects_all_y,dc_subjects_y,dc_dates_all_y,dc_date_collected_y,dc_date_issued_y,dc_descriptions_all_y,dc_abstract_y,dc_geoLocations_all_y,dc_geo_places_y,dc_rightsList_y,dc_fundingReferences_y,dc_relatedIdentifiers_all_y,dc_isVersionOf_y,dc_rel_client_y,dc_rel_provider_y,dc_rel_media_y,dc_rel_versionOf_y,dc_rel_versions_y,dc_rel_parts_y,dc_rel_partOf_y,dc_rel_citations_y,dc_rel_references_y,dc_error_y
81,_datasets/administrative-law-judge-decisions.md,data_rescue_project,Administrative Law Judge Decisions,National Labor Relations Board,National Labor Relations Board,nlrb.gov,https://www.nlrb.gov/cases-decisions/decisions/administrative-law-judge-decisions,None,2025-05-14,False,None,Labor & Employment,1,Administrative Law Judge Decisions,1008,https://nlrbresearch.com/NLRB/NLRB_DB?_search=type%3A+%22ALJ%22,PDF,Finished,0.000,None,NLRB-R,Captured as part of NLRB Research a free database a researcher made.,nlrbresearch.com,None,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,_datasets/affirmatively-furthering-fair-housing-affh-data.md,data_rescue_project,Affirmatively Furthering Fair Housing (AFFH) Data,Department of Housing and Urban Development,Department of Housing and Urban Development,hud.gov,https://www.hud.gov/AFFH,None,2025-05-19,True,https://datacatalog.urban.org/dataset/us-department-housing-and-urban-development-affirmatively-furthering-fair-housing-hud-affh,Housing & Community Development,1,Affirmatively Furthering Fair Housing (AFFH) Data,1037,https://urban-data-catalog.s3.us-east-1.amazonaws.com/drupal-root-live/2025/04/03/housing-and-communities/hud-affh/data.zip,ZIP,Finished,0.876,2024-12-18,UI,"This dataset contains all data, documentation, and file resources linked to on the main US Department of Housing and Urban Development’s Affirmatively Furthering Fair Housing (AFFH) page and powering the AFFH tool.",urban-data-catalog.s3.us-east-1.amazonaws.com,None,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_2 = df[df['doi'].notna()].copy()

In [69]:
df_2.isna().mean().sort_values(ascending=False).head(50)

dc_contentUrl_x            1.000000
dc_rel_parts_y             1.000000
dc_reason_y                1.000000
dc_reason_x                1.000000
dc_rel_parts_x             1.000000
dc_rel_partOf_x            1.000000
dc_rel_partOf_y            1.000000
dc_contentUrl_y            1.000000
dc_rel_versions_y          0.998894
dc_rel_references_x        0.998894
dc_rel_versions_x          0.998894
dc_rel_references_y        0.998894
description                0.997788
metadata_url               0.981570
dc_contributors_names_x    0.980833
dc_contributors_names_y    0.980833
dc_rel_citations_x         0.968669
dc_rel_citations_y         0.968669
dc_error_y                 0.935864
dc_error_x                 0.935864
notes                      0.747512
dc_geo_places_y            0.666790
dc_geo_places_x            0.666790
dc_date_collected_x        0.636933
dc_date_collected_y        0.636933
dc_subjects_x              0.293771
dc_subjects_y              0.293771
format                     0.189090
size                       0.117213
dc_rel_versionOf_x         0.106156
dc_rel_versionOf_y         0.106156
dc_language_x              0.093255
dc_language_y              0.093255
dc_isVersionOf_x           0.089569
dc_isVersionOf_y           0.089569
dc_version_y               0.073719
dc_version_x               0.073719
dc_source_x                0.067084
dc_source_y                0.067084
dc_schemaVersion_x         0.064873
dc_schemaVersion_y         0.064873
dc_creators_types_y        0.064504
dc_creators_types_x        0.064504
dc_geoLocations_all_y      0.064136
dc_url_y                   0.064136
dc_contributors_all_y      0.064136
dc_abstract_y              0.064136
dc_rightsList_y            0.064136
dc_state_y                 0.064136
dc_isActive_y              0.064136
dtype: float64

In [ ]:
threshold = 0.97

cols_to_drop = df_2.columns[
    df_2.isna().mean() >= threshold
]

df_2 = df_2.drop(columns=cols_to_drop)

print(f'Dropped {len(cols_to_drop)} columns')

Dropped 16 columns

In [71]:
df_2.columns

Index(['file', 'schema', 'title', 'organization', 'agency', 'websites',
       'data_source', 'last_modified', 'metadata_available', 'category',
       ...
       'dc_rightsList_y', 'dc_fundingReferences_y',
       'dc_relatedIdentifiers_all_y', 'dc_isVersionOf_y', 'dc_rel_client_y',
       'dc_rel_provider_y', 'dc_rel_media_y', 'dc_rel_versionOf_y',
       'dc_rel_citations_y', 'dc_error_y'],
      dtype='object', length=142)

In [ ]:
df = df_2.copy()

In [8]:
df['notes'].isna().sum()

1859

In [5]:
sorted(df.columns)

['Unnamed: 0',
 'agency',
 'category',
 'data_source',
 'dc_abstract_x',
 'dc_abstract_y',
 'dc_alternateIdentifiers_x',
 'dc_alternateIdentifiers_y',
 'dc_citationCount_x',
 'dc_citationCount_y',
 'dc_contributors_all_x',
 'dc_contributors_all_y',
 'dc_created_x',
 'dc_created_y',
 'dc_creators_all_x',
 'dc_creators_all_y',
 'dc_creators_names_x',
 'dc_creators_names_y',
 'dc_creators_types_x',
 'dc_creators_types_y',
 'dc_date_collected_x',
 'dc_date_collected_y',
 'dc_date_issued_x',
 'dc_date_issued_y',
 'dc_dates_all_x',
 'dc_dates_all_y',
 'dc_descriptions_all_x',
 'dc_descriptions_all_y',
 'dc_downloadCount_x',
 'dc_downloadCount_y',
 'dc_error_x',
 'dc_error_y',
 'dc_fundingReferences_x',
 'dc_fundingReferences_y',
 'dc_geoLocations_all_x',
 'dc_geoLocations_all_y',
 'dc_geo_places_x',
 'dc_geo_places_y',
 'dc_identifiers_x',
 'dc_identifiers_y',
 'dc_isActive_x',
 'dc_isActive_y',
 'dc_isVersionOf_x',
 'dc_isVersionOf_y',
 'dc_language_x',
 'dc_language_y',
 'dc_metadataVersion_x',
 'dc_metadataVersion_y',
 'dc_ok_x',
 'dc_ok_y',
 'dc_partCount_x',
 'dc_partCount_y',
 'dc_partOfCount_x',
 'dc_partOfCount_y',
 'dc_prefix_x',
 'dc_prefix_y',
 'dc_publicationYear_x',
 'dc_publicationYear_y',
 'dc_published_x',
 'dc_published_y',
 'dc_publisher_x',
 'dc_publisher_y',
 'dc_referenceCount_x',
 'dc_referenceCount_y',
 'dc_registered_x',
 'dc_registered_y',
 'dc_rel_citations_x',
 'dc_rel_citations_y',
 'dc_rel_client_x',
 'dc_rel_client_y',
 'dc_rel_media_x',
 'dc_rel_media_y',
 'dc_rel_provider_x',
 'dc_rel_provider_y',
 'dc_rel_versionOf_x',
 'dc_rel_versionOf_y',
 'dc_relatedIdentifiers_all_x',
 'dc_relatedIdentifiers_all_y',
 'dc_rightsList_x',
 'dc_rightsList_y',
 'dc_schemaVersion_x',
 'dc_schemaVersion_y',
 'dc_source_x',
 'dc_source_y',
 'dc_state_x',
 'dc_state_y',
 'dc_status_x',
 'dc_status_y',
 'dc_subjects_all_x',
 'dc_subjects_all_y',
 'dc_subjects_x',
 'dc_subjects_y',
 'dc_suffix_x',
 'dc_suffix_y',
 'dc_title_x',
 'dc_title_y',
 'dc_titles_all_x',
 'dc_titles_all_y',
 'dc_types_bibtex_x',
 'dc_types_bibtex_y',
 'dc_types_citeproc_x',
 'dc_types_citeproc_y',
 'dc_types_resourceTypeGeneral_x',
 'dc_types_resourceTypeGeneral_y',
 'dc_types_ris_x',
 'dc_types_ris_y',
 'dc_types_schemaOrg_x',
 'dc_types_schemaOrg_y',
 'dc_updated_x',
 'dc_updated_y',
 'dc_url_x',
 'dc_url_y',
 'dc_versionCount_x',
 'dc_versionCount_y',
 'dc_versionOfCount_x',
 'dc_versionOfCount_y',
 'dc_version_x',
 'dc_version_y',
 'dc_viewCount_x',
 'dc_viewCount_y',
 'doi',
 'doi_guess',
 'doi_norm',
 'domain',
 'download_date',
 'file',
 'format',
 'id',
 'last_modified',
 'maintainer',
 'metadata_available',
 'notes',
 'organization',
 'project_id',
 'project_title',
 'resource_count',
 'schema',
 'size',
 'status',
 'title',
 'url',
 'version',
 'websites']

In [ ]:
df['group'] = 'A_drp'

In [ ]:
df = df.drop(columns=['Unnamed: 0'], errors='ignore')

x_cols = [c for c in df.columns if c.endswith('_x')]
y_cols = [c for c in df.columns if c.endswith('_y')]

df = df.rename(columns={c: c[:-2] for c in x_cols})

df = df.drop(columns=y_cols, errors='ignore')

pct_no_abstract = df['dc_abstract'].isna().mean() * 100
print(f'% no abstract: {pct_no_abstract:.2f}%')

% no abstract: 6.41%

In [ ]:
df = df[df['dc_abstract'].notna() & df['dc_title'].notna()].copy()

print('rows after dropping no abstract or no title:', len(df))

rows after dropping no abstract or no title: 2539

In [52]:
df = add_flagged_column(df, abstract_col='dc_abstract', title_col='dc_title')

In [53]:
df.to_csv('00_data/drp_withdoi.csv')

# Next: 02_eda_dgm_dgf